<?php

namespace Database\Seeders;

use App\Models\Privilege;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class PrivilegesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        Privilege::query()->truncate();
        Privilege::upsert([
            ['slug' => 'dashboard_can_view', 'name' => 'Global: Can View Site Dashboard',
                'description' => 'This allow the user to access the staff dashboard panel. The user will see the modules they are privileged to use only.'],
            ['slug' => 'torrent_can_view', 'name' => 'Torrents: Can Search & View',
                'description' => 'Can Search and View Torrents on The Site'],
            ['slug' => 'torrent_can_create', 'name' => 'Torrents: Can Create/Upload',
                'description' => 'User Can Create a New Torrent on the Site'],
            ['slug' => 'torrent_can_bypass_modq', 'name' => 'Torrents: Bypass Moderation',
                'description' => 'When a User Creates a New Torrent, the Torrent will bypass the Moderation Queue'],
            ['slug' => 'torrent_can_moderate', 'name' => 'Torrents: Can Moderate Torrents',
                'description' => 'User can Approve, Postpone, or Reject Torrents - Both in Moderation Queue and On-Site'],
            ['slug' => 'torrent_can_update', 'name' => 'Torrents: Can Edit Torrents',
                'description' => 'Can Edit the Fields which have been granted permission. This grants access to the necessary pages.'],
            ['slug' => 'torrent_can_update_title', 'name' => 'Torrents: Can Edit Titles',
                'description' => 'Can Edit Torrent Titles'],
            ['slug' => 'torrent_can_update_description', 'name' => 'Torrents: Can Edit Descriptions',
                'description' => ' '],
            ['slug' => 'torrent_can_update_mediainfo', 'name' => 'Torrents: Can Edit MediaInfo',
                'description' => ' '],
            ['slug' => 'torrent_can_update_category', 'name' => 'Torrents: Can Edit Category',
                'description' => ' '],
            ['slug' => 'torrent_can_update_type', 'name' => 'Torrents: Can Edit Type', 'description' => ' '],
            ['slug' => 'torrent_can_update_resolution', 'name' => 'Torrents: Can Edit Resolution', 'description' => ' '],
            ['slug' => 'torrent_can_update_meta_ids', 'name' => 'Torrents: Can Edit Meta Id\'s', 'description' => ' '],
            ['slug' => 'torrent_can_update_special', 'name' => 'Torrents: Can Edit Special Attributes', 'description' => ' '],
            ['slug' => 'torrent_can_delete', 'name' => 'Torrents: Can Delete', 'description' => ' '],
            ['slug' => 'torrent_can_download', 'name' => 'Torrents: Can Download', 'description' => ' '],
            ['slug' => 'torrent_can_request_reseed', 'name' => 'Torrents: Can Request Reseed', 'description' => ' '],
            ['slug' => 'torrent_can_bump', 'name' => 'Torrents: Can Bump', 'description' => ' '],
            ['slug' => 'torrent_can_internal', 'name' => 'Torrents: Can Internal', 'description' => ' '],
            ['slug' => 'torrent_can_freeleech', 'name' => 'Torrents: Can Freeleech', 'description' => ' '],
            ['slug' => 'torrent_can_doubleupload', 'name' => 'Torrents: Can Double Upload', 'description' => ' '],
            ['slug' => 'torrent_can_personal_release', 'name' => 'Torrents: Can Personal Release', 'description' => ' '],
            ['slug' => 'torrent_can_sticky', 'name' => 'Torrents: Can Sticky', 'description' => ' '],
            ['slug' => 'torrent_can_feature', 'name' => 'Torrents: Can Feature', 'description' => ' '],
            ['slug' => 'torrent_can_revoke_feature', 'name' => 'torrent_can_revoke_feature', 'description' => ' '],
            ['slug' => 'request_can_view', 'name' => 'request_can_view', 'description' => ' '],
            ['slug' => 'request_can_create', 'name' => 'request_can_create', 'description' => ' '],
            ['slug' => 'request_can_update', 'name' => 'request_can_update', 'description' => ' '],
            ['slug' => 'request_can_update_title', 'name' => 'request_can_update_title', 'description' => ' '],
            ['slug' => 'request_can_update_description', 'name' => 'request_can_update_description', 'description' => ' '],
            ['slug' => 'request_can_update_category', 'name' => 'request_can_update_category', 'description' => ' '],
            ['slug' => 'request_can_update_type', 'name' => 'request_can_update_type', 'description' => ' '],
            ['slug' => 'request_can_update_resolution', 'name' => 'request_can_update_resolution', 'description' => ' '],
            ['slug' => 'request_can_update_meta_ids', 'name' => 'request_can_update_meta_ids', 'description' => ' '],
            ['slug' => 'request_can_delete', 'name' => 'request_can_delete', 'description' => ' '],
            ['slug' => 'request_can_approve', 'name' => 'request_can_approve', 'description' => ' '],
            ['slug' => 'request_can_deny', 'name' => 'request_can_deny', 'description' => ' '],
            ['slug' => 'request_can_reset', 'name' => 'request_can_reset', 'description' => ' '],
            ['slug' => 'comment_can_view', 'name' => 'comment_can_view', 'description' => ' '],
            ['slug' => 'comment_can_create', 'name' => 'comment_can_create', 'description' => ' '],
            ['slug' => 'comment_can_update', 'name' => 'comment_can_update', 'description' => ' '],
            ['slug' => 'comment_can_delete', 'name' => 'comment_can_delete', 'description' => ' '],
            ['slug' => 'chat_can_moderate', 'name' => 'chat_can_moderate', 'description' => ' '],
            ['slug' => 'comments_can_moderate', 'name' => 'chat_can_moderate', 'description' => ' '],
            ['slug' => 'forums_can_view', 'name' => 'forum_can_view', 'description' => ' '],
            ['slug' => 'forums_can_sticky', 'name' => 'forum_can_sticky', 'description' => ' '],
            ['slug' => 'forums_can_bump', 'name' => 'forum_can_bump', 'description' => ' '],
            ['slug' => 'forums_can_create_topic', 'name' => 'forum_can_create_topic', 'description' => ' '],
            ['slug' => 'forums_can_delete_topic', 'name' => 'forum_can_delete_topic', 'description' => ' '],
            ['slug' => 'forums_can_comment', 'name' => 'forum_can_comment', 'description' => ' '],
            ['slug' => 'forums_can_update_comment', 'name' => 'forum_can_update_comment', 'description' => ' '],
            ['slug' => 'forums_can_delete_comment', 'name' => 'forum_can_delete_comment', 'description' => ' '],
            ['slug' => 'forums_sudo', 'name' => 'Forums: All Privileges on All Forums', 'description' => ' '],
            ['slug' => 'playlist_can_view', 'name' => 'playlist_can_view', 'description' => ' '],
            ['slug' => 'playlist_can_create', 'name' => 'playlist_can_create', 'description' => ' '],
            ['slug' => 'playlist_can_update', 'name' => 'playlist_can_update', 'description' => ' '],
            ['slug' => 'playlist_can_delete', 'name' => 'playlist_can_delete', 'description' => ' '],
            ['slug' => 'playlist_can_download_all', 'name' => 'playlist_can_download_all', 'description' => ' '],
            ['slug' => 'polls_can_view', 'name' => 'polls_can_view', 'description' => ' '],
            ['slug' => 'polls_can_vote', 'name' => 'polls_can_vote', 'description' => ' '],
            ['slug' => 'polls_can_create', 'name' => 'polls_can_create', 'description' => ' '],
            ['slug' => 'polls_can_delete', 'name' => 'polls_can_delete', 'description' => ' '],
            ['slug' => 'subtitle_can_view', 'name' => 'subtitle_can_view', 'description' => ' '],
            ['slug' => 'subtitle_can_create', 'name' => 'subtitle_can_create', 'description' => ' '],
            ['slug' => 'subtitle_can_update', 'name' => 'subtitle_can_update', 'description' => ' '],
            ['slug' => 'subtitle_can_delete', 'name' => 'subtitle_can_delete', 'description' => ' '],
            ['slug' => 'subtitle_can_download', 'name' => 'subtitle_can_download', 'description' => ' '],
            ['slug' => 'movie_can_create', 'name' => 'movie_can_create', 'description' => ' '],
            ['slug' => 'movie_can_update', 'name' => 'movie_can_update', 'description' => ' '],
            ['slug' => 'movie_can_update_title', 'name' => 'movie_can_update_title', 'description' => ' '],
            ['slug' => 'movie_can_update_original_language', 'name' => 'movie_can_update_original_language', 'description' => ' '],
            ['slug' => 'movie_can_update_backdrop', 'name' => 'movie_can_update_backdrop', 'description' => ' '],
            ['slug' => 'movie_can_update_poster', 'name' => 'movie_can_update_poster', 'description' => ' '],
            ['slug' => 'movie_can_update_overview', 'name' => 'movie_can_update_overview', 'description' => ' '],
            ['slug' => 'movie_can_update_tagline', 'name' => 'movie_can_update_tagline', 'description' => ' '],
            ['slug' => 'movie_can_update_runtime', 'name' => 'movie_can_update_runtime', 'description' => ' '],
            ['slug' => 'movie_can_update_status', 'name' => 'movie_can_update_status', 'description' => ' '],
            ['slug' => 'tv_can_create', 'name' => 'tv_can_create', 'description' => ' '],
            ['slug' => 'tv_can_update', 'name' => 'tv_can_update', 'description' => ' '],
            ['slug' => 'tv_can_update_title', 'name' => 'tv_can_update_title', 'description' => ' '],
            ['slug' => 'tv_can_update_original_language', 'name' => 'tv_can_update_original_language', 'description' => ' '],
            ['slug' => 'tv_can_update_backdrop', 'name' => 'tv_can_update_backdrop', 'description' => ' '],
            ['slug' => 'tv_can_update_poster', 'name' => 'tv_can_update_poster', 'description' => ' '],
            ['slug' => 'tv_can_update_overview', 'name' => 'tv_can_update_overview', 'description' => ' '],
            ['slug' => 'tv_can_update_tagline', 'name' => 'tv_can_update_tagline', 'description' => ' '],
            ['slug' => 'tv_can_update_runtime', 'name' => 'tv_can_update_runtime', 'description' => ' '],
            ['slug' => 'tv_can_update_status', 'name' => 'tv_can_update_status', 'description' => ' '],
            ['slug' => 'users_view_private', 'name' => 'Users: View Private Profiles', 'description' => ' '],
            ['slug' => 'users_view_privileges', 'name' => 'Users: View Privileges', 'description' => ' '],
            ['slug' => 'users_edit_privileges', 'name' => 'Users: Edit Users Privileges', 'description' => ' '],
            ['slug' => 'users_view_personal', 'name' => 'Users: View Users Personal Information', 'description' => ' '],
            ['slug' => 'users_edit_personal', 'name' => 'Users: Edit Users Personal Information', 'description' => ' '],
            ['slug' => 'users_view_security', 'name' => 'Users: View Users Security Information', 'description' => ' '],
            ['slug' => 'users_edit_security', 'name' => 'Users: Edit Users Security Information', 'description' => ' '],
            ['slug' => 'users_view_invites', 'name' => 'Users: View Users Invites', 'description' => ' '],
            ['slug' => 'users_bypass_notification_preferences', 'name'=> 'Users: Bypass a User Notification Preferences', 'description' => ' '],
            ['slug' => 'user_special_freeleech', 'name'=> 'User: Special Freeleech', 'description' => ' '],
            ['slug' => 'user_special_double_upload', 'name'=> 'User: Special Double Upload', 'description' => ' '],
            ['slug' => 'user_can_invite', 'name'=> 'User: Can Invite Users', 'description' => ' '],
            ['slug' => 'user_can_private_message', 'name'=> 'User: Can Send Private Messages', 'description' => ' '],
            ['slug' => 'user_can_report', 'name'=> 'User: Can Report Items on Site', 'description' => ' '],
            ['slug' => 'user_can_rss', 'name'=> 'User: Can Use RSS Feature', 'description' => ' '],
            ['slug' => 'helpdesk_can_submit', 'name'=> 'Helpdesk: Can Submit Ticket', 'description' => ' '],
            ['slug' => 'helpdesk_can_handle', 'name'=> 'Helpdesk: Can Handle Ticket', 'description' => ' '],
            ['slug' => 'helpdesk_can_edit', 'name'=> 'Helpdesk: Can Edit Ticket', 'description' => ' '],
            ['slug' => 'helpdesk_can_delete', 'name'=> 'Helpdesk: Can Delete Ticket', 'description' => ' '],
            ['slug' => 'can_login', 'name' => 'Global: Can Login', 'description' => ' '],
            ['slug' => 'active_user', 'name' => 'Global: Is Active User', 'description' => ' '],
            ['slug' => 'album_can_view', 'name' => 'Gallery Albums: Can View', 'description' => ' '],
            ['slug' => 'album_can_create', 'name' => 'Gallery Albums: Can Create', 'description' => ' '],
            ['slug' => 'album_can_delete', 'name' => 'Gallery Albums: Can Delete', 'description' => ' '],
            ['slug' => 'graveyard_can_cancel', 'name' => 'Graveyard: Can Cancel Resurrection', 'description' => ' '],
            ['slug' => 'stats_can_view', 'name' => 'Site Stats: Can View Site Stats Pages', 'description' => ' ']
        ], ['slug'], ['name', 'description']);
        $this->call(RolePrivileges::class);
        Schema::enableForeignKeyConstraints();
    }
}
