<?php
/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

namespace Database\Seeders;

use App\Models\Region;
use Illuminate\Database\Seeder;

class RegionsTableSeeder extends Seeder
{
    private $regions;

    public function __construct()
    {
        $this->regions = $this->getRegions();
    }

    /**
     * Auto generated seed file.
     */
    public function run(): void
    {
        foreach ($this->regions as $region) {
            Region::updateOrCreate($region);
        }
    }

    private function getRegions(): array
    {
        return [
            [
                'id'       => 1,
                'name'     => 'AFG',
                'slug'     => 'afg',
                'position' => 0,
            ],
            [
                'id'       => 2,
                'name'     => 'AIA',
                'slug'     => 'aia',
                'position' => 1,
            ],
            [
                'id'       => 3,
                'name'     => 'ALA',
                'slug'     => 'ala',
                'position' => 2,
            ],
            [
                'id'       => 4,
                'name'     => 'ALG',
                'slug'     => 'alg',
                'position' => 3,
            ],
            [
                'id'       => 5,
                'name'     => 'AND',
                'slug'     => 'and',
                'position' => 4,
            ],
            [
                'id'       => 6,
                'name'     => 'ANG',
                'slug'     => 'ang',
                'position' => 5,
            ],
            [
                'id'       => 7,
                'name'     => 'ARG',
                'slug'     => 'arg',
                'position' => 6,
            ],
            [
                'id'       => 8,
                'name'     => 'ARM',
                'slug'     => 'arm',
                'position' => 7,
            ],
            [
                'id'       => 9,
                'name'     => 'ARU',
                'slug'     => 'aru',
                'position' => 8,
            ],
            [
                'id'       => 10,
                'name'     => 'ASA',
                'slug'     => 'asa',
                'position' => 9,
            ],
            [
                'id'       => 11,
                'name'     => 'ATA',
                'slug'     => 'ata',
                'position' => 10,
            ],
            [
                'id'       => 12,
                'name'     => 'ATF',
                'slug'     => 'atf',
                'position' => 11,
            ],
            [
                'id'       => 13,
                'name'     => 'ATG',
                'slug'     => 'atg',
                'position' => 12,
            ],
            [
                'id'       => 14,
                'name'     => 'AUS',
                'slug'     => 'aus',
                'position' => 13,
            ],
            [
                'id'       => 15,
                'name'     => 'AUT',
                'slug'     => 'aut',
                'position' => 14,
            ],
            [
                'id'       => 16,
                'name'     => 'AZE',
                'slug'     => 'aze',
                'position' => 15,
            ],
            [
                'id'       => 17,
                'name'     => 'BAH',
                'slug'     => 'bah',
                'position' => 16,
            ],
            [
                'id'       => 18,
                'name'     => 'BAN',
                'slug'     => 'ban',
                'position' => 17,
            ],
            [
                'id'       => 19,
                'name'     => 'BDI',
                'slug'     => 'bdi',
                'position' => 18,
            ],
            [
                'id'       => 20,
                'name'     => 'BEL',
                'slug'     => 'bel',
                'position' => 19,
            ],
            [
                'id'       => 21,
                'name'     => 'BEN',
                'slug'     => 'ben',
                'position' => 20,
            ],
            [
                'id'       => 22,
                'name'     => 'BER',
                'slug'     => 'ber',
                'position' => 21,
            ],
            [
                'id'       => 23,
                'name'     => 'BES',
                'slug'     => 'bes',
                'position' => 22,
            ],
            [
                'id'       => 24,
                'name'     => 'BFA',
                'slug'     => 'bfa',
                'position' => 23,
            ],
            [
                'id'       => 25,
                'name'     => 'BHR',
                'slug'     => 'bhr',
                'position' => 24,
            ],
            [
                'id'       => 26,
                'name'     => 'BHU',
                'slug'     => 'bhu',
                'position' => 25,
            ],
            [
                'id'       => 27,
                'name'     => 'BIH',
                'slug'     => 'bih',
                'position' => 26,
            ],
            [
                'id'       => 28,
                'name'     => 'BLM',
                'slug'     => 'blm',
                'position' => 27,
            ],
            [
                'id'       => 29,
                'name'     => 'BLR',
                'slug'     => 'blr',
                'position' => 28,
            ],
            [
                'id'       => 30,
                'name'     => 'BLZ',
                'slug'     => 'blz',
                'position' => 29,
            ],
            [
                'id'       => 31,
                'name'     => 'BOL',
                'slug'     => 'bol',
                'position' => 30,
            ],
            [
                'id'       => 32,
                'name'     => 'BOT',
                'slug'     => 'bot',
                'position' => 31,
            ],
            [
                'id'       => 33,
                'name'     => 'BRA',
                'slug'     => 'bra',
                'position' => 32,
            ],
            [
                'id'       => 34,
                'name'     => 'BRB',
                'slug'     => 'brb',
                'position' => 33,
            ],
            [
                'id'       => 35,
                'name'     => 'BRU',
                'slug'     => 'bru',
                'position' => 34,
            ],
            [
                'id'       => 36,
                'name'     => 'BVT',
                'slug'     => 'bvt',
                'position' => 35,
            ],
            [
                'id'       => 37,
                'name'     => 'CAM',
                'slug'     => 'cam',
                'position' => 36,
            ],
            [
                'id'       => 38,
                'name'     => 'CAN',
                'slug'     => 'can',
                'position' => 37,
            ],
            [
                'id'       => 39,
                'name'     => 'CAY',
                'slug'     => 'cay',
                'position' => 38,
            ],
            [
                'id'       => 40,
                'name'     => 'CCK',
                'slug'     => 'cck',
                'position' => 39,
            ],
            [
                'id'       => 41,
                'name'     => 'CEE',
                'slug'     => 'cee',
                'position' => 40,
            ],
            [
                'id'       => 42,
                'name'     => 'CGO',
                'slug'     => 'cgo',
                'position' => 41,
            ],
            [
                'id'       => 43,
                'name'     => 'CHA',
                'slug'     => 'cha',
                'position' => 42,
            ],
            [
                'id'       => 44,
                'name'     => 'CHI',
                'slug'     => 'chi',
                'position' => 43,
            ],
            [
                'id'       => 45,
                'name'     => 'CHN',
                'slug'     => 'chn',
                'position' => 44,
            ],
            [
                'id'       => 46,
                'name'     => 'CIV',
                'slug'     => 'civ',
                'position' => 45,
            ],
            [
                'id'       => 47,
                'name'     => 'CMR',
                'slug'     => 'cmr',
                'position' => 46,
            ],
            [
                'id'       => 48,
                'name'     => 'COD',
                'slug'     => 'cod',
                'position' => 47,
            ],
            [
                'id'       => 49,
                'name'     => 'COK',
                'slug'     => 'cok',
                'position' => 48,
            ],
            [
                'id'       => 50,
                'name'     => 'COL',
                'slug'     => 'col',
                'position' => 49,
            ],
            [
                'id'       => 51,
                'name'     => 'COM',
                'slug'     => 'com',
                'position' => 50,
            ],
            [
                'id'       => 52,
                'name'     => 'CPV',
                'slug'     => 'cpv',
                'position' => 51,
            ],
            [
                'id'       => 53,
                'name'     => 'CRC',
                'slug'     => 'crc',
                'position' => 52,
            ],
            [
                'id'       => 54,
                'name'     => 'CRO',
                'slug'     => 'cro',
                'position' => 53,
            ],
            [
                'id'       => 55,
                'name'     => 'CTA',
                'slug'     => 'cta',
                'position' => 54,
            ],
            [
                'id'       => 56,
                'name'     => 'CUB',
                'slug'     => 'cub',
                'position' => 55,
            ],
            [
                'id'       => 57,
                'name'     => 'CUW',
                'slug'     => 'cuw',
                'position' => 56,
            ],
            [
                'id'       => 58,
                'name'     => 'CXR',
                'slug'     => 'cxr',
                'position' => 57,
            ],
            [
                'id'       => 59,
                'name'     => 'CYP',
                'slug'     => 'cyp',
                'position' => 58,
            ],
            [
                'id'       => 60,
                'name'     => 'DJI',
                'slug'     => 'dji',
                'position' => 59,
            ],
            [
                'id'       => 61,
                'name'     => 'DMA',
                'slug'     => 'dma',
                'position' => 60,
            ],
            [
                'id'       => 62,
                'name'     => 'DOM',
                'slug'     => 'dom',
                'position' => 61,
            ],
            [
                'id'       => 63,
                'name'     => 'ECU',
                'slug'     => 'ecu',
                'position' => 62,
            ],
            [
                'id'       => 64,
                'name'     => 'EGY',
                'slug'     => 'egy',
                'position' => 63,
            ],
            [
                'id'       => 65,
                'name'     => 'ENG',
                'slug'     => 'eng',
                'position' => 64,
            ],
            [
                'id'       => 66,
                'name'     => 'EQG',
                'slug'     => 'eqg',
                'position' => 65,
            ],
            [
                'id'       => 67,
                'name'     => 'ERI',
                'slug'     => 'eri',
                'position' => 66,
            ],
            [
                'id'       => 68,
                'name'     => 'ESH',
                'slug'     => 'esh',
                'position' => 67,
            ],
            [
                'id'       => 69,
                'name'     => 'ESP',
                'slug'     => 'esp',
                'position' => 68,
            ],
            [
                'id'       => 70,
                'name'     => 'ETH',
                'slug'     => 'eth',
                'position' => 69,
            ],
            [
                'id'       => 71,
                'name'     => 'FIJ',
                'slug'     => 'fij',
                'position' => 70,
            ],
            [
                'id'       => 72,
                'name'     => 'FLK',
                'slug'     => 'flk',
                'position' => 71,
            ],
            [
                'id'       => 73,
                'name'     => 'FRA',
                'slug'     => 'fra',
                'position' => 72,
            ],
            [
                'id'       => 74,
                'name'     => 'FRO',
                'slug'     => 'fro',
                'position' => 73,
            ],
            [
                'id'       => 75,
                'name'     => 'FSM',
                'slug'     => 'fsm',
                'position' => 74,
            ],
            [
                'id'       => 76,
                'name'     => 'GAB',
                'slug'     => 'gab',
                'position' => 75,
            ],
            [
                'id'       => 77,
                'name'     => 'GAM',
                'slug'     => 'gam',
                'position' => 76,
            ],
            [
                'id'       => 78,
                'name'     => 'GBR',
                'slug'     => 'gbr',
                'position' => 77,
            ],
            [
                'id'       => 79,
                'name'     => 'GEO',
                'slug'     => 'geo',
                'position' => 78,
            ],
            [
                'id'       => 80,
                'name'     => 'GER',
                'slug'     => 'ger',
                'position' => 79,
            ],
            [
                'id'       => 81,
                'name'     => 'GGY',
                'slug'     => 'ggy',
                'position' => 80,
            ],
            [
                'id'       => 82,
                'name'     => 'GHA',
                'slug'     => 'gha',
                'position' => 81,
            ],
            [
                'id'       => 83,
                'name'     => 'GIB',
                'slug'     => 'gib',
                'position' => 82,
            ],
            [
                'id'       => 84,
                'name'     => 'GLP',
                'slug'     => 'glp',
                'position' => 83,
            ],
            [
                'id'       => 85,
                'name'     => 'GNB',
                'slug'     => 'gnb',
                'position' => 84,
            ],
            [
                'id'       => 86,
                'name'     => 'GRE',
                'slug'     => 'gre',
                'position' => 85,
            ],
            [
                'id'       => 87,
                'name'     => 'GRL',
                'slug'     => 'grl',
                'position' => 86,
            ],
            [
                'id'       => 88,
                'name'     => 'GRN',
                'slug'     => 'grn',
                'position' => 87,
            ],
            [
                'id'       => 89,
                'name'     => 'GUA',
                'slug'     => 'gua',
                'position' => 88,
            ],
            [
                'id'       => 90,
                'name'     => 'GUF',
                'slug'     => 'guf',
                'position' => 89,
            ],
            [
                'id'       => 91,
                'name'     => 'GUI',
                'slug'     => 'gui',
                'position' => 90,
            ],
            [
                'id'       => 92,
                'name'     => 'GUM',
                'slug'     => 'gum',
                'position' => 91,
            ],
            [
                'id'       => 93,
                'name'     => 'GUY',
                'slug'     => 'guy',
                'position' => 92,
            ],
            [
                'id'       => 94,
                'name'     => 'HAI',
                'slug'     => 'hai',
                'position' => 93,
            ],
            [
                'id'       => 95,
                'name'     => 'HKG',
                'slug'     => 'hkg',
                'position' => 94,
            ],
            [
                'id'       => 96,
                'name'     => 'HMD',
                'slug'     => 'hmd',
                'position' => 95,
            ],
            [
                'id'       => 97,
                'name'     => 'HON',
                'slug'     => 'hon',
                'position' => 96,
            ],
            [
                'id'       => 98,
                'name'     => 'HUN',
                'slug'     => 'hun',
                'position' => 97,
            ],
            [
                'id'       => 99,
                'name'     => 'IDN',
                'slug'     => 'idn',
                'position' => 98,
            ],
            [
                'id'       => 100,
                'name'     => 'IMN',
                'slug'     => 'imn',
                'position' => 99,
            ],
            [
                'id'       => 101,
                'name'     => 'IND',
                'slug'     => 'ind',
                'position' => 100,
            ],
            [
                'id'       => 102,
                'name'     => 'IOT',
                'slug'     => 'iot',
                'position' => 101,
            ],
            [
                'id'       => 103,
                'name'     => 'IRL',
                'slug'     => 'irl',
                'position' => 102,
            ],
            [
                'id'       => 104,
                'name'     => 'IRN',
                'slug'     => 'irn',
                'position' => 103,
            ],
            [
                'id'       => 105,
                'name'     => 'IRQ',
                'slug'     => 'irq',
                'position' => 104,
            ],
            [
                'id'       => 106,
                'name'     => 'ISL',
                'slug'     => 'isl',
                'position' => 105,
            ],
            [
                'id'       => 107,
                'name'     => 'ISR',
                'slug'     => 'isr',
                'position' => 106,
            ],
            [
                'id'       => 108,
                'name'     => 'ITA',
                'slug'     => 'ita',
                'position' => 107,
            ],
            [
                'id'       => 109,
                'name'     => 'JAM',
                'slug'     => 'jam',
                'position' => 108,
            ],
            [
                'id'       => 110,
                'name'     => 'JEY',
                'slug'     => 'jey',
                'position' => 109,
            ],
            [
                'id'       => 111,
                'name'     => 'JOR',
                'slug'     => 'jor',
                'position' => 110,
            ],
            [
                'id'       => 112,
                'name'     => 'JPN',
                'slug'     => 'jpn',
                'position' => 111,
            ],
            [
                'id'       => 113,
                'name'     => 'KAZ',
                'slug'     => 'kaz',
                'position' => 112,
            ],
            [
                'id'       => 114,
                'name'     => 'KEN',
                'slug'     => 'ken',
                'position' => 113,
            ],
            [
                'id'       => 115,
                'name'     => 'KGZ',
                'slug'     => 'kgz',
                'position' => 114,
            ],
            [
                'id'       => 116,
                'name'     => 'KIR',
                'slug'     => 'kir',
                'position' => 115,
            ],
            [
                'id'       => 117,
                'name'     => 'KNA',
                'slug'     => 'kna',
                'position' => 116,
            ],
            [
                'id'       => 118,
                'name'     => 'KOR',
                'slug'     => 'kor',
                'position' => 117,
            ],
            [
                'id'       => 119,
                'name'     => 'KSA',
                'slug'     => 'ksa',
                'position' => 118,
            ],
            [
                'id'       => 120,
                'name'     => 'KUW',
                'slug'     => 'kuw',
                'position' => 119,
            ],
            [
                'id'       => 121,
                'name'     => 'KVX',
                'slug'     => 'kvx',
                'position' => 120,
            ],
            [
                'id'       => 122,
                'name'     => 'LAO',
                'slug'     => 'lao',
                'position' => 121,
            ],
            [
                'id'       => 123,
                'name'     => 'LBN',
                'slug'     => 'lbn',
                'position' => 122,
            ],
            [
                'id'       => 124,
                'name'     => 'LBR',
                'slug'     => 'lbr',
                'position' => 123,
            ],
            [
                'id'       => 125,
                'name'     => 'LBY',
                'slug'     => 'lby',
                'position' => 124,
            ],
            [
                'id'       => 126,
                'name'     => 'LCA',
                'slug'     => 'lca',
                'position' => 125,
            ],
            [
                'id'       => 127,
                'name'     => 'LES',
                'slug'     => 'les',
                'position' => 126,
            ],
            [
                'id'       => 128,
                'name'     => 'LIE',
                'slug'     => 'lie',
                'position' => 127,
            ],
            [
                'id'       => 129,
                'name'     => 'LKA',
                'slug'     => 'lka',
                'position' => 128,
            ],
            [
                'id'       => 130,
                'name'     => 'LUX',
                'slug'     => 'lux',
                'position' => 129,
            ],
            [
                'id'       => 131,
                'name'     => 'MAC',
                'slug'     => 'mac',
                'position' => 130,
            ],
            [
                'id'       => 132,
                'name'     => 'MAD',
                'slug'     => 'mad',
                'position' => 131,
            ],
            [
                'id'       => 133,
                'name'     => 'MAF',
                'slug'     => 'maf',
                'position' => 132,
            ],
            [
                'id'       => 134,
                'name'     => 'MAR',
                'slug'     => 'mar',
                'position' => 133,
            ],
            [
                'id'       => 135,
                'name'     => 'MAS',
                'slug'     => 'mas',
                'position' => 134,
            ],
            [
                'id'       => 136,
                'name'     => 'MDA',
                'slug'     => 'mda',
                'position' => 135,
            ],
            [
                'id'       => 137,
                'name'     => 'MDV',
                'slug'     => 'mdv',
                'position' => 136,
            ],
            [
                'id'       => 138,
                'name'     => 'MEX',
                'slug'     => 'mex',
                'position' => 137,
            ],
            [
                'id'       => 139,
                'name'     => 'MHL',
                'slug'     => 'mhl',
                'position' => 138,
            ],
            [
                'id'       => 140,
                'name'     => 'MKD',
                'slug'     => 'mkd',
                'position' => 139,
            ],
            [
                'id'       => 141,
                'name'     => 'MLI',
                'slug'     => 'mli',
                'position' => 140,
            ],
            [
                'id'       => 142,
                'name'     => 'MLT',
                'slug'     => 'mlt',
                'position' => 141,
            ],
            [
                'id'       => 143,
                'name'     => 'MNG',
                'slug'     => 'mng',
                'position' => 142,
            ],
            [
                'id'       => 144,
                'name'     => 'MNP',
                'slug'     => 'mnp',
                'position' => 143,
            ],
            [
                'id'       => 145,
                'name'     => 'MON',
                'slug'     => 'mon',
                'position' => 144,
            ],
            [
                'id'       => 146,
                'name'     => 'MOZ',
                'slug'     => 'moz',
                'position' => 145,
            ],
            [
                'id'       => 147,
                'name'     => 'MRI',
                'slug'     => 'mri',
                'position' => 146,
            ],
            [
                'id'       => 148,
                'name'     => 'MSR',
                'slug'     => 'msr',
                'position' => 147,
            ],
            [
                'id'       => 149,
                'name'     => 'MTN',
                'slug'     => 'mtn',
                'position' => 148,
            ],
            [
                'id'       => 150,
                'name'     => 'MTQ',
                'slug'     => 'mtq',
                'position' => 149,
            ],
            [
                'id'       => 151,
                'name'     => 'MWI',
                'slug'     => 'mwi',
                'position' => 150,
            ],
            [
                'id'       => 152,
                'name'     => 'MYA',
                'slug'     => 'mya',
                'position' => 151,
            ],
            [
                'id'       => 153,
                'name'     => 'MYT',
                'slug'     => 'myt',
                'position' => 152,
            ],
            [
                'id'       => 154,
                'name'     => 'NAM',
                'slug'     => 'nam',
                'position' => 153,
            ],
            [
                'id'       => 155,
                'name'     => 'NCA',
                'slug'     => 'nca',
                'position' => 154,
            ],
            [
                'id'       => 156,
                'name'     => 'NCL',
                'slug'     => 'ncl',
                'position' => 155,
            ],
            [
                'id'       => 157,
                'name'     => 'NEP',
                'slug'     => 'nep',
                'position' => 156,
            ],
            [
                'id'       => 158,
                'name'     => 'NFK',
                'slug'     => 'nfk',
                'position' => 157,
            ],
            [
                'id'       => 159,
                'name'     => 'NIG',
                'slug'     => 'nig',
                'position' => 158,
            ],
            [
                'id'       => 160,
                'name'     => 'NIR',
                'slug'     => 'nir',
                'position' => 159,
            ],
            [
                'id'       => 161,
                'name'     => 'NIU',
                'slug'     => 'niu',
                'position' => 160,
            ],
            [
                'id'       => 162,
                'name'     => 'NLD',
                'slug'     => 'nld',
                'position' => 161,
            ],
            [
                'id'       => 163,
                'name'     => 'NOR',
                'slug'     => 'nor',
                'position' => 162,
            ],
            [
                'id'       => 164,
                'name'     => 'NRU',
                'slug'     => 'nru',
                'position' => 163,
            ],
            [
                'id'       => 165,
                'name'     => 'NZL',
                'slug'     => 'nzl',
                'position' => 164,
            ],
            [
                'id'       => 166,
                'name'     => 'OMA',
                'slug'     => 'oma',
                'position' => 165,
            ],
            [
                'id'       => 167,
                'name'     => 'PAK',
                'slug'     => 'pak',
                'position' => 166,
            ],
            [
                'id'       => 168,
                'name'     => 'PAN',
                'slug'     => 'pan',
                'position' => 167,
            ],
            [
                'id'       => 169,
                'name'     => 'PAR',
                'slug'     => 'par',
                'position' => 168,
            ],
            [
                'id'       => 170,
                'name'     => 'PCN',
                'slug'     => 'pcn',
                'position' => 169,
            ],
            [
                'id'       => 171,
                'name'     => 'PER',
                'slug'     => 'per',
                'position' => 170,
            ],
            [
                'id'       => 172,
                'name'     => 'PHI',
                'slug'     => 'phi',
                'position' => 171,
            ],
            [
                'id'       => 173,
                'name'     => 'PLE',
                'slug'     => 'ple',
                'position' => 172,
            ],
            [
                'id'       => 174,
                'name'     => 'PLW',
                'slug'     => 'plw',
                'position' => 173,
            ],
            [
                'id'       => 175,
                'name'     => 'PNG',
                'slug'     => 'png',
                'position' => 174,
            ],
            [
                'id'       => 176,
                'name'     => 'POL',
                'slug'     => 'pol',
                'position' => 175,
            ],
            [
                'id'       => 177,
                'name'     => 'POR',
                'slug'     => 'por',
                'position' => 176,
            ],
            [
                'id'       => 178,
                'name'     => 'PRK',
                'slug'     => 'prk',
                'position' => 177,
            ],
            [
                'id'       => 179,
                'name'     => 'PUR',
                'slug'     => 'pur',
                'position' => 178,
            ],
            [
                'id'       => 180,
                'name'     => 'QAT',
                'slug'     => 'qat',
                'position' => 179,
            ],
            [
                'id'       => 181,
                'name'     => 'REU',
                'slug'     => 'reu',
                'position' => 180,
            ],
            [
                'id'       => 182,
                'name'     => 'ROU',
                'slug'     => 'rou',
                'position' => 181,
            ],
            [
                'id'       => 183,
                'name'     => 'RSA',
                'slug'     => 'rsa',
                'position' => 182,
            ],
            [
                'id'       => 184,
                'name'     => 'RUS',
                'slug'     => 'rus',
                'position' => 183,
            ],
            [
                'id'       => 185,
                'name'     => 'RWA',
                'slug'     => 'rwa',
                'position' => 184,
            ],
            [
                'id'       => 186,
                'name'     => 'SAM',
                'slug'     => 'sam',
                'position' => 185,
            ],
            [
                'id'       => 187,
                'name'     => 'SCO',
                'slug'     => 'sco',
                'position' => 186,
            ],
            [
                'id'       => 188,
                'name'     => 'SDN',
                'slug'     => 'sdn',
                'position' => 187,
            ],
            [
                'id'       => 189,
                'name'     => 'SEN',
                'slug'     => 'sen',
                'position' => 188,
            ],
            [
                'id'       => 190,
                'name'     => 'SEY',
                'slug'     => 'sey',
                'position' => 189,
            ],
            [
                'id'       => 191,
                'name'     => 'SGS',
                'slug'     => 'sgs',
                'position' => 190,
            ],
            [
                'id'       => 192,
                'name'     => 'SHN',
                'slug'     => 'shn',
                'position' => 191,
            ],
            [
                'id'       => 193,
                'name'     => 'SIN',
                'slug'     => 'sin',
                'position' => 192,
            ],
            [
                'id'       => 194,
                'name'     => 'SJM',
                'slug'     => 'sjm',
                'position' => 193,
            ],
            [
                'id'       => 195,
                'name'     => 'SLE',
                'slug'     => 'sle',
                'position' => 194,
            ],
            [
                'id'       => 196,
                'name'     => 'SLV',
                'slug'     => 'slv',
                'position' => 195,
            ],
            [
                'id'       => 197,
                'name'     => 'SMR',
                'slug'     => 'smr',
                'position' => 196,
            ],
            [
                'id'       => 198,
                'name'     => 'SOL',
                'slug'     => 'sol',
                'position' => 197,
            ],
            [
                'id'       => 199,
                'name'     => 'SOM',
                'slug'     => 'som',
                'position' => 198,
            ],
            [
                'id'       => 200,
                'name'     => 'SPM',
                'slug'     => 'spm',
                'position' => 199,
            ],
            [
                'id'       => 201,
                'name'     => 'SRB',
                'slug'     => 'srb',
                'position' => 200,
            ],
            [
                'id'       => 202,
                'name'     => 'SSD',
                'slug'     => 'ssd',
                'position' => 201,
            ],
            [
                'id'       => 203,
                'name'     => 'STP',
                'slug'     => 'stp',
                'position' => 202,
            ],
            [
                'id'       => 204,
                'name'     => 'SUI',
                'slug'     => 'sui',
                'position' => 203,
            ],
            [
                'id'       => 205,
                'name'     => 'SUR',
                'slug'     => 'sur',
                'position' => 204,
            ],
            [
                'id'       => 206,
                'name'     => 'SWZ',
                'slug'     => 'swz',
                'position' => 205,
            ],
            [
                'id'       => 207,
                'name'     => 'SXM',
                'slug'     => 'sxm',
                'position' => 206,
            ],
            [
                'id'       => 208,
                'name'     => 'SYR',
                'slug'     => 'syr',
                'position' => 207,
            ],
            [
                'id'       => 209,
                'name'     => 'TAH',
                'slug'     => 'tah',
                'position' => 208,
            ],
            [
                'id'       => 210,
                'name'     => 'TAN',
                'slug'     => 'tan',
                'position' => 209,
            ],
            [
                'id'       => 211,
                'name'     => 'TCA',
                'slug'     => 'tca',
                'position' => 210,
            ],
            [
                'id'       => 212,
                'name'     => 'TGA',
                'slug'     => 'tga',
                'position' => 211,
            ],
            [
                'id'       => 213,
                'name'     => 'THA',
                'slug'     => 'tha',
                'position' => 212,
            ],
            [
                'id'       => 214,
                'name'     => 'TJK',
                'slug'     => 'tjk',
                'position' => 213,
            ],
            [
                'id'       => 215,
                'name'     => 'TKL',
                'slug'     => 'tkl',
                'position' => 214,
            ],
            [
                'id'       => 216,
                'name'     => 'TKM',
                'slug'     => 'tkm',
                'position' => 215,
            ],
            [
                'id'       => 217,
                'name'     => 'TLS',
                'slug'     => 'tls',
                'position' => 216,
            ],
            [
                'id'       => 218,
                'name'     => 'TOG',
                'slug'     => 'tog',
                'position' => 217,
            ],
            [
                'id'       => 219,
                'name'     => 'TRI',
                'slug'     => 'tri',
                'position' => 218,
            ],
            [
                'id'       => 220,
                'name'     => 'TUN',
                'slug'     => 'tun',
                'position' => 219,
            ],
            [
                'id'       => 221,
                'name'     => 'TUR',
                'slug'     => 'tur',
                'position' => 220,
            ],
            [
                'id'       => 222,
                'name'     => 'TUV',
                'slug'     => 'tuv',
                'position' => 221,
            ],
            [
                'id'       => 223,
                'name'     => 'TWN',
                'slug'     => 'twn',
                'position' => 222,
            ],
            [
                'id'       => 224,
                'name'     => 'UAE',
                'slug'     => 'uae',
                'position' => 223,
            ],
            [
                'id'       => 225,
                'name'     => 'UGA',
                'slug'     => 'uga',
                'position' => 224,
            ],
            [
                'id'       => 226,
                'name'     => 'UKR',
                'slug'     => 'ukr',
                'position' => 225,
            ],
            [
                'id'       => 227,
                'name'     => 'UMI',
                'slug'     => 'umi',
                'position' => 226,
            ],
            [
                'id'       => 228,
                'name'     => 'URU',
                'slug'     => 'uru',
                'position' => 227,
            ],
            [
                'id'       => 229,
                'name'     => 'USA',
                'slug'     => 'usa',
                'position' => 228,
            ],
            [
                'id'       => 230,
                'name'     => 'UZB',
                'slug'     => 'uzb',
                'position' => 229,
            ],
            [
                'id'       => 231,
                'name'     => 'VAN',
                'slug'     => 'van',
                'position' => 230,
            ],
            [
                'id'       => 232,
                'name'     => 'VAT',
                'slug'     => 'vat',
                'position' => 231,
            ],
            [
                'id'       => 233,
                'name'     => 'VEN',
                'slug'     => 'ven',
                'position' => 232,
            ],
            [
                'id'       => 234,
                'name'     => 'VGB',
                'slug'     => 'vgb',
                'position' => 233,
            ],
            [
                'id'       => 235,
                'name'     => 'VIE',
                'slug'     => 'vie',
                'position' => 234,
            ],
            [
                'id'       => 236,
                'name'     => 'VIN',
                'slug'     => 'vin',
                'position' => 235,
            ],
            [
                'id'       => 237,
                'name'     => 'VIR',
                'slug'     => 'vir',
                'position' => 236,
            ],
            [
                'id'       => 238,
                'name'     => 'WAL',
                'slug'     => 'wal',
                'position' => 237,
            ],
            [
                'id'       => 239,
                'name'     => 'WLF',
                'slug'     => 'wlf',
                'position' => 238,
            ],
            [
                'id'       => 240,
                'name'     => 'YEM',
                'slug'     => 'yem',
                'position' => 239,
            ],
            [
                'id'       => 241,
                'name'     => 'ZAM',
                'slug'     => 'zam',
                'position' => 240,
            ],
            [
                'id'       => 242,
                'name'     => 'ZIM',
                'slug'     => 'zim',
                'position' => 241,
            ],
        ];
    }
}
