<?php

namespace Database\Seeders;

use App\Models\Role;
use Illuminate\Database\Seeder;

class RolesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Role::upsert([
            ['slug'               => 'sudo',
                'name'            => 'System Operator',
                'position'        => 999,
                'icon'            => config('other.font-awesome').' fa-user-secret',
                'color'           => '#f92672',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'root',
                'name'            => 'Owner',
                'position'        => 998,
                'icon'            => config('other.font-awesome').' fa-user-secret',
                'color'           => '#00abff',
                'effect'          => 'url(/img/sparkels.gif)',
                'system_required' => true, ],
            ['slug'               => 'bot',
                'name'            => 'Bot',
                'position'        => 997,
                'icon'            => config('other.font-awesome').' fa-file-code-o',
                'color'           => '#f1c40f',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'pruned',
                'name'            => 'Pruned',
                'position'        => 001,
                'icon'            => config('other.font-awesome').' fa-user-secret',
                'color'           => '#00abff',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'disabled',
                'name'            => 'Disabled',
                'position'        => 002,
                'icon'            => config('other.font-awesome').' fa-user-secret',
                'color'           => '#00abff',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'validating',
                'name'            => 'Validating',
                'position'        => 003,
                'icon'            => config('other.font-awesome').' fa-question-circle',
                'color'           => '#95A5A6',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'guest',
                'name'            => 'Guests',
                'position'        => 004,
                'icon'            => config('other.font-awesome').' fa-question-circle',
                'color'           => '#575757',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'banned',
                'name'            => 'Banned',
                'position'        => 005,
                'icon'            => config('other.font-awesome').' fa-ban',
                'color'           => 'red',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'user',
                'name'            => 'User',
                'position'        => 100,
                'icon'            => config('other.font-awesome').' fa-user',
                'color'           => '#7289DA',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'group_1',
                'name'            => 'PowerUser',
                'position'        => 101,
                'icon'            => config('other.font-awesome').' fa-user-circle',
                'color'           => '#3c78d8',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'group_2',
                'name'            => 'SuperUser',
                'position'        => 102,
                'icon'            => config('other.font-awesome').' fa-power-off',
                'color'           => '#1155cc',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'group_3',
                'name'            => 'ExtremeUser',
                'position'        => 103,
                'icon'            => config('other.font-awesome').' fa-bolt',
                'color'           => '#1c4587',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'group_4',
                'name'            => 'InsaneUser',
                'position'        => 104,
                'icon'            => config('other.font-awesome').' fa-rocket',
                'color'           => '#1c4587',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'group_5',
                'name'            => 'GodUser',
                'position'        => 105,
                'icon'            => config('other.font-awesome').' fa-space-shuttle',
                'color'           => '#3d0f4a',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'group_6',
                'name'            => 'Veteran',
                'position'        => 106,
                'icon'            => config('other.font-awesome').' fa-key',
                'color'           => '#1c4587',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'group_7',
                'name'            => 'Seeder',
                'position'        => 107,
                'icon'            => config('other.font-awesome').' fa-hdd',
                'color'           => '#1c4587',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'group_8',
                'name'            => 'Archivist',
                'position'        => 108,
                'icon'            => config('other.font-awesome').' fa-server',
                'color'           => '#1c4587',
                'effect'          => 'url(/img/sparkels.gif)',
                'system_required' => true, ],
            ['slug'               => 'leech',
                'name'            => 'Leech',
                'position'        => 99,
                'icon'            => config('other.font-awesome').' fa-bug',
                'color'           => '#96281B',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'uploader',
                'name'            => 'Uploader',
                'position'        => 801,
                'icon'            => config('other.font-awesome').' fa-upload',
                'color'           => '#2ECC71',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'recruiter',
                'name'            => 'Recruiter',
                'position'        => 802,
                'icon'            => config('other.font-awesome').' fa-user-secret',
                'color'           => '#00abff',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'trustee',
                'name'            => 'Trustee',
                'position'        => 803,
                'icon'            => config('other.font-awesome').' fa-shield',
                'color'           => '#BF55EC',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'supporter',
                'name'            => 'Supporter',
                'position'        => 201,
                'icon'            => config('other.font-awesome').' fa-star',
                'color'           => '#de7402',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'fls',
                'name'            => 'FLS',
                'position'        => 901,
                'icon'            => config('other.font-awesome').' fa-medkit',
                'color'           => '#de0602',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'editor',
                'name'            => 'Editor',
                'position'        => 900,
                'icon'            => config('other.font-awesome').' fa-user-edit',
                'color'           => '#00a808',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'internal',
                'name'            => 'Internal',
                'position'        => 902,
                'icon'            => config('other.font-awesome').' fa-magic',
                'color'           => '#BAAF92',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'moderator',
                'name'            => 'Moderator',
                'position'        => 903,
                'icon'            => config('other.font-awesome').' fa-user-cog',
                'color'           => '#4757cc',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'admin',
                'name'            => 'Administrator',
                'position'        => 904,
                'icon'            => config('other.font-awesome').' fa-tools',
                'color'           => '#4757cc',
                'effect'          => null,
                'system_required' => true, ],
            ['slug'               => 'coder',
                'name'            => 'Coder',
                'position'        => 905,
                'icon'            => config('other.font-awesome').' fa-user-secret',
                'color'           => '#00d5ff',
                'effect'          => null,
                'system_required' => true, ],

        ],
                ['slug'],
                ['name']);
    }
}
