<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 =>
            array (
                'id' => 103,
                'forum_id' => 18,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            1 =>
            array (
                'id' => 104,
                'forum_id' => 18,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            2 =>
            array (
                'id' => 105,
                'forum_id' => 18,
                'group_id' => 3,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            3 =>
            array (
                'id' => 106,
                'forum_id' => 18,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            4 =>
            array (
                'id' => 107,
                'forum_id' => 18,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            5 =>
            array (
                'id' => 108,
                'forum_id' => 18,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            6 =>
            array (
                'id' => 109,
                'forum_id' => 18,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            7 =>
            array (
                'id' => 110,
                'forum_id' => 18,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            8 =>
            array (
                'id' => 111,
                'forum_id' => 18,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            9 =>
            array (
                'id' => 112,
                'forum_id' => 18,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            10 =>
            array (
                'id' => 113,
                'forum_id' => 18,
                'group_id' => 11,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            11 =>
            array (
                'id' => 114,
                'forum_id' => 18,
                'group_id' => 12,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            12 =>
            array (
                'id' => 115,
                'forum_id' => 18,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            13 =>
            array (
                'id' => 116,
                'forum_id' => 18,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            14 =>
            array (
                'id' => 117,
                'forum_id' => 18,
                'group_id' => 15,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            15 =>
            array (
                'id' => 118,
                'forum_id' => 18,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            16 =>
            array (
                'id' => 119,
                'forum_id' => 18,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            17 =>
            array (
                'id' => 120,
                'forum_id' => 18,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            18 =>
            array (
                'id' => 130,
                'forum_id' => 29,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            19 =>
            array (
                'id' => 131,
                'forum_id' => 29,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            20 =>
            array (
                'id' => 132,
                'forum_id' => 29,
                'group_id' => 3,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            21 =>
            array (
                'id' => 133,
                'forum_id' => 29,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            22 =>
            array (
                'id' => 134,
                'forum_id' => 29,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            23 =>
            array (
                'id' => 135,
                'forum_id' => 29,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            24 =>
            array (
                'id' => 136,
                'forum_id' => 29,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            25 =>
            array (
                'id' => 137,
                'forum_id' => 29,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            26 =>
            array (
                'id' => 138,
                'forum_id' => 29,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            27 =>
            array (
                'id' => 139,
                'forum_id' => 29,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            28 =>
            array (
                'id' => 140,
                'forum_id' => 29,
                'group_id' => 11,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            29 =>
            array (
                'id' => 141,
                'forum_id' => 29,
                'group_id' => 12,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            30 =>
            array (
                'id' => 142,
                'forum_id' => 29,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            31 =>
            array (
                'id' => 143,
                'forum_id' => 29,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            32 =>
            array (
                'id' => 144,
                'forum_id' => 29,
                'group_id' => 15,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            33 =>
            array (
                'id' => 145,
                'forum_id' => 29,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            34 =>
            array (
                'id' => 146,
                'forum_id' => 29,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            35 =>
            array (
                'id' => 147,
                'forum_id' => 29,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            36 =>
            array (
                'id' => 150,
                'forum_id' => 31,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            37 =>
            array (
                'id' => 151,
                'forum_id' => 31,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            38 =>
            array (
                'id' => 152,
                'forum_id' => 31,
                'group_id' => 3,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            39 =>
            array (
                'id' => 153,
                'forum_id' => 31,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            40 =>
            array (
                'id' => 154,
                'forum_id' => 31,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            41 =>
            array (
                'id' => 155,
                'forum_id' => 31,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            42 =>
            array (
                'id' => 156,
                'forum_id' => 31,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            43 =>
            array (
                'id' => 157,
                'forum_id' => 31,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            44 =>
            array (
                'id' => 158,
                'forum_id' => 31,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            45 =>
            array (
                'id' => 159,
                'forum_id' => 31,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            46 =>
            array (
                'id' => 160,
                'forum_id' => 31,
                'group_id' => 11,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            47 =>
            array (
                'id' => 161,
                'forum_id' => 31,
                'group_id' => 12,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            48 =>
            array (
                'id' => 162,
                'forum_id' => 31,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            49 =>
            array (
                'id' => 163,
                'forum_id' => 31,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            50 =>
            array (
                'id' => 164,
                'forum_id' => 31,
                'group_id' => 15,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            51 =>
            array (
                'id' => 165,
                'forum_id' => 31,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            52 =>
            array (
                'id' => 166,
                'forum_id' => 31,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            53 =>
            array (
                'id' => 167,
                'forum_id' => 31,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            54 =>
            array (
                'id' => 170,
                'forum_id' => 32,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            55 =>
            array (
                'id' => 171,
                'forum_id' => 32,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            56 =>
            array (
                'id' => 172,
                'forum_id' => 32,
                'group_id' => 3,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            57 =>
            array (
                'id' => 173,
                'forum_id' => 32,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            58 =>
            array (
                'id' => 174,
                'forum_id' => 32,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            59 =>
            array (
                'id' => 175,
                'forum_id' => 32,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            60 =>
            array (
                'id' => 176,
                'forum_id' => 32,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            61 =>
            array (
                'id' => 177,
                'forum_id' => 32,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            62 =>
            array (
                'id' => 178,
                'forum_id' => 32,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            63 =>
            array (
                'id' => 179,
                'forum_id' => 32,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            64 =>
            array (
                'id' => 180,
                'forum_id' => 32,
                'group_id' => 11,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            65 =>
            array (
                'id' => 181,
                'forum_id' => 32,
                'group_id' => 12,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            66 =>
            array (
                'id' => 182,
                'forum_id' => 32,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            67 =>
            array (
                'id' => 183,
                'forum_id' => 32,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            68 =>
            array (
                'id' => 184,
                'forum_id' => 32,
                'group_id' => 15,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            69 =>
            array (
                'id' => 185,
                'forum_id' => 32,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            70 =>
            array (
                'id' => 186,
                'forum_id' => 32,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            71 =>
            array (
                'id' => 187,
                'forum_id' => 32,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            72 =>
            array (
                'id' => 190,
                'forum_id' => 33,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            73 =>
            array (
                'id' => 191,
                'forum_id' => 33,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            74 =>
            array (
                'id' => 192,
                'forum_id' => 33,
                'group_id' => 3,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            75 =>
            array (
                'id' => 193,
                'forum_id' => 33,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            76 =>
            array (
                'id' => 194,
                'forum_id' => 33,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            77 =>
            array (
                'id' => 195,
                'forum_id' => 33,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            78 =>
            array (
                'id' => 196,
                'forum_id' => 33,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            79 =>
            array (
                'id' => 197,
                'forum_id' => 33,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            80 =>
            array (
                'id' => 198,
                'forum_id' => 33,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            81 =>
            array (
                'id' => 199,
                'forum_id' => 33,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            82 =>
            array (
                'id' => 200,
                'forum_id' => 33,
                'group_id' => 11,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            83 =>
            array (
                'id' => 201,
                'forum_id' => 33,
                'group_id' => 12,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            84 =>
            array (
                'id' => 202,
                'forum_id' => 33,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            85 =>
            array (
                'id' => 203,
                'forum_id' => 33,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            86 =>
            array (
                'id' => 204,
                'forum_id' => 33,
                'group_id' => 15,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            87 =>
            array (
                'id' => 205,
                'forum_id' => 33,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            88 =>
            array (
                'id' => 206,
                'forum_id' => 33,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            89 =>
            array (
                'id' => 207,
                'forum_id' => 33,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            90 =>
            array (
                'id' => 210,
                'forum_id' => 35,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            91 =>
            array (
                'id' => 211,
                'forum_id' => 35,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            92 =>
            array (
                'id' => 212,
                'forum_id' => 35,
                'group_id' => 3,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            93 =>
            array (
                'id' => 213,
                'forum_id' => 35,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            94 =>
            array (
                'id' => 214,
                'forum_id' => 35,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            95 =>
            array (
                'id' => 215,
                'forum_id' => 35,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            96 =>
            array (
                'id' => 216,
                'forum_id' => 35,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            97 =>
            array (
                'id' => 217,
                'forum_id' => 35,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            98 =>
            array (
                'id' => 218,
                'forum_id' => 35,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            99 =>
            array (
                'id' => 219,
                'forum_id' => 35,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            100 =>
            array (
                'id' => 220,
                'forum_id' => 35,
                'group_id' => 11,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            101 =>
            array (
                'id' => 221,
                'forum_id' => 35,
                'group_id' => 12,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            102 =>
            array (
                'id' => 222,
                'forum_id' => 35,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            103 =>
            array (
                'id' => 223,
                'forum_id' => 35,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            104 =>
            array (
                'id' => 224,
                'forum_id' => 35,
                'group_id' => 15,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            105 =>
            array (
                'id' => 225,
                'forum_id' => 35,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            106 =>
            array (
                'id' => 226,
                'forum_id' => 35,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            107 =>
            array (
                'id' => 227,
                'forum_id' => 35,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            108 =>
            array (
                'id' => 230,
                'forum_id' => 36,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            109 =>
            array (
                'id' => 231,
                'forum_id' => 36,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            110 =>
            array (
                'id' => 232,
                'forum_id' => 36,
                'group_id' => 3,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            111 =>
            array (
                'id' => 233,
                'forum_id' => 36,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            112 =>
            array (
                'id' => 234,
                'forum_id' => 36,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            113 =>
            array (
                'id' => 235,
                'forum_id' => 36,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            114 =>
            array (
                'id' => 236,
                'forum_id' => 36,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            115 =>
            array (
                'id' => 237,
                'forum_id' => 36,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            116 =>
            array (
                'id' => 238,
                'forum_id' => 36,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            117 =>
            array (
                'id' => 239,
                'forum_id' => 36,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            118 =>
            array (
                'id' => 240,
                'forum_id' => 36,
                'group_id' => 11,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            119 =>
            array (
                'id' => 241,
                'forum_id' => 36,
                'group_id' => 12,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            120 =>
            array (
                'id' => 242,
                'forum_id' => 36,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            121 =>
            array (
                'id' => 243,
                'forum_id' => 36,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            122 =>
            array (
                'id' => 244,
                'forum_id' => 36,
                'group_id' => 15,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            123 =>
            array (
                'id' => 245,
                'forum_id' => 36,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            124 =>
            array (
                'id' => 246,
                'forum_id' => 36,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            125 =>
            array (
                'id' => 247,
                'forum_id' => 36,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            126 =>
            array (
                'id' => 250,
                'forum_id' => 37,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            127 =>
            array (
                'id' => 251,
                'forum_id' => 37,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            128 =>
            array (
                'id' => 253,
                'forum_id' => 37,
                'group_id' => 3,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            129 =>
            array (
                'id' => 254,
                'forum_id' => 37,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            130 =>
            array (
                'id' => 255,
                'forum_id' => 37,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            131 =>
            array (
                'id' => 256,
                'forum_id' => 37,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            132 =>
            array (
                'id' => 257,
                'forum_id' => 37,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            133 =>
            array (
                'id' => 258,
                'forum_id' => 37,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            134 =>
            array (
                'id' => 259,
                'forum_id' => 37,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            135 =>
            array (
                'id' => 260,
                'forum_id' => 37,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            136 =>
            array (
                'id' => 261,
                'forum_id' => 37,
                'group_id' => 11,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            137 =>
            array (
                'id' => 262,
                'forum_id' => 37,
                'group_id' => 12,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            138 =>
            array (
                'id' => 263,
                'forum_id' => 37,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            139 =>
            array (
                'id' => 264,
                'forum_id' => 37,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            140 =>
            array (
                'id' => 265,
                'forum_id' => 37,
                'group_id' => 15,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            141 =>
            array (
                'id' => 266,
                'forum_id' => 37,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            142 =>
            array (
                'id' => 267,
                'forum_id' => 37,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            143 =>
            array (
                'id' => 268,
                'forum_id' => 37,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            144 =>
            array (
                'id' => 269,
                'forum_id' => 38,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            145 =>
            array (
                'id' => 270,
                'forum_id' => 38,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            146 =>
            array (
                'id' => 271,
                'forum_id' => 38,
                'group_id' => 3,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            147 =>
            array (
                'id' => 272,
                'forum_id' => 38,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            148 =>
            array (
                'id' => 273,
                'forum_id' => 38,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            149 =>
            array (
                'id' => 274,
                'forum_id' => 38,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            150 =>
            array (
                'id' => 275,
                'forum_id' => 38,
                'group_id' => 7,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            151 =>
            array (
                'id' => 276,
                'forum_id' => 38,
                'group_id' => 8,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            152 =>
            array (
                'id' => 277,
                'forum_id' => 38,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            153 =>
            array (
                'id' => 278,
                'forum_id' => 38,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            154 =>
            array (
                'id' => 279,
                'forum_id' => 38,
                'group_id' => 11,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            155 =>
            array (
                'id' => 280,
                'forum_id' => 38,
                'group_id' => 12,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            156 =>
            array (
                'id' => 281,
                'forum_id' => 38,
                'group_id' => 13,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            157 =>
            array (
                'id' => 282,
                'forum_id' => 38,
                'group_id' => 14,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            158 =>
            array (
                'id' => 283,
                'forum_id' => 38,
                'group_id' => 15,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            159 =>
            array (
                'id' => 284,
                'forum_id' => 38,
                'group_id' => 16,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            160 =>
            array (
                'id' => 285,
                'forum_id' => 38,
                'group_id' => 17,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            161 =>
            array (
                'id' => 286,
                'forum_id' => 38,
                'group_id' => 18,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            162 =>
            array (
                'id' => 287,
                'forum_id' => 39,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            163 =>
            array (
                'id' => 290,
                'forum_id' => 39,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            164 =>
            array (
                'id' => 291,
                'forum_id' => 39,
                'group_id' => 3,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            165 =>
            array (
                'id' => 292,
                'forum_id' => 39,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            166 =>
            array (
                'id' => 293,
                'forum_id' => 39,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            167 =>
            array (
                'id' => 294,
                'forum_id' => 39,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            168 =>
            array (
                'id' => 295,
                'forum_id' => 39,
                'group_id' => 7,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            169 =>
            array (
                'id' => 296,
                'forum_id' => 39,
                'group_id' => 8,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            170 =>
            array (
                'id' => 297,
                'forum_id' => 39,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            171 =>
            array (
                'id' => 298,
                'forum_id' => 39,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            172 =>
            array (
                'id' => 299,
                'forum_id' => 39,
                'group_id' => 11,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            173 =>
            array (
                'id' => 300,
                'forum_id' => 39,
                'group_id' => 12,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            174 =>
            array (
                'id' => 301,
                'forum_id' => 39,
                'group_id' => 13,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            175 =>
            array (
                'id' => 302,
                'forum_id' => 39,
                'group_id' => 14,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            176 =>
            array (
                'id' => 303,
                'forum_id' => 39,
                'group_id' => 15,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            177 =>
            array (
                'id' => 304,
                'forum_id' => 39,
                'group_id' => 16,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            178 =>
            array (
                'id' => 305,
                'forum_id' => 39,
                'group_id' => 17,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            179 =>
            array (
                'id' => 306,
                'forum_id' => 39,
                'group_id' => 18,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            180 =>
            array (
                'id' => 309,
                'forum_id' => 40,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            181 =>
            array (
                'id' => 310,
                'forum_id' => 40,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            182 =>
            array (
                'id' => 311,
                'forum_id' => 40,
                'group_id' => 3,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            183 =>
            array (
                'id' => 312,
                'forum_id' => 40,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            184 =>
            array (
                'id' => 313,
                'forum_id' => 40,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            185 =>
            array (
                'id' => 314,
                'forum_id' => 40,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            186 =>
            array (
                'id' => 315,
                'forum_id' => 40,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            187 =>
            array (
                'id' => 316,
                'forum_id' => 40,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            188 =>
            array (
                'id' => 317,
                'forum_id' => 40,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            189 =>
            array (
                'id' => 318,
                'forum_id' => 40,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            190 =>
            array (
                'id' => 319,
                'forum_id' => 40,
                'group_id' => 11,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            191 =>
            array (
                'id' => 320,
                'forum_id' => 40,
                'group_id' => 12,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            192 =>
            array (
                'id' => 322,
                'forum_id' => 40,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            193 =>
            array (
                'id' => 323,
                'forum_id' => 40,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            194 =>
            array (
                'id' => 324,
                'forum_id' => 40,
                'group_id' => 15,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            195 =>
            array (
                'id' => 325,
                'forum_id' => 40,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            196 =>
            array (
                'id' => 326,
                'forum_id' => 40,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            197 =>
            array (
                'id' => 327,
                'forum_id' => 40,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            198 =>
            array (
                'id' => 330,
                'forum_id' => 42,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            199 =>
            array (
                'id' => 331,
                'forum_id' => 42,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            200 =>
            array (
                'id' => 332,
                'forum_id' => 42,
                'group_id' => 3,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            201 =>
            array (
                'id' => 333,
                'forum_id' => 42,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            202 =>
            array (
                'id' => 334,
                'forum_id' => 42,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            203 =>
            array (
                'id' => 335,
                'forum_id' => 42,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            204 =>
            array (
                'id' => 336,
                'forum_id' => 42,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            205 =>
            array (
                'id' => 337,
                'forum_id' => 42,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            206 =>
            array (
                'id' => 338,
                'forum_id' => 42,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            207 =>
            array (
                'id' => 339,
                'forum_id' => 42,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            208 =>
            array (
                'id' => 358,
                'forum_id' => 44,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            209 =>
            array (
                'id' => 359,
                'forum_id' => 44,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            210 =>
            array (
                'id' => 360,
                'forum_id' => 44,
                'group_id' => 3,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            211 =>
            array (
                'id' => 361,
                'forum_id' => 44,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            212 =>
            array (
                'id' => 362,
                'forum_id' => 44,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            213 =>
            array (
                'id' => 363,
                'forum_id' => 44,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            214 =>
            array (
                'id' => 364,
                'forum_id' => 44,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            215 =>
            array (
                'id' => 365,
                'forum_id' => 44,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            216 =>
            array (
                'id' => 366,
                'forum_id' => 44,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            217 =>
            array (
                'id' => 367,
                'forum_id' => 44,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            218 =>
            array (
                'id' => 368,
                'forum_id' => 44,
                'group_id' => 11,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            219 =>
            array (
                'id' => 369,
                'forum_id' => 44,
                'group_id' => 12,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            220 =>
            array (
                'id' => 370,
                'forum_id' => 44,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            221 =>
            array (
                'id' => 371,
                'forum_id' => 44,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            222 =>
            array (
                'id' => 372,
                'forum_id' => 44,
                'group_id' => 15,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            223 =>
            array (
                'id' => 373,
                'forum_id' => 44,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            224 =>
            array (
                'id' => 374,
                'forum_id' => 44,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            225 =>
            array (
                'id' => 375,
                'forum_id' => 44,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            226 =>
            array (
                'id' => 376,
                'forum_id' => 45,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            227 =>
            array (
                'id' => 377,
                'forum_id' => 45,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            228 =>
            array (
                'id' => 378,
                'forum_id' => 45,
                'group_id' => 3,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            229 =>
            array (
                'id' => 379,
                'forum_id' => 45,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            230 =>
            array (
                'id' => 380,
                'forum_id' => 45,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            231 =>
            array (
                'id' => 381,
                'forum_id' => 45,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            232 =>
            array (
                'id' => 382,
                'forum_id' => 45,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            233 =>
            array (
                'id' => 383,
                'forum_id' => 45,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            234 =>
            array (
                'id' => 384,
                'forum_id' => 45,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            235 =>
            array (
                'id' => 385,
                'forum_id' => 45,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            236 =>
            array (
                'id' => 386,
                'forum_id' => 45,
                'group_id' => 11,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            237 =>
            array (
                'id' => 387,
                'forum_id' => 45,
                'group_id' => 12,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            238 =>
            array (
                'id' => 388,
                'forum_id' => 45,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            239 =>
            array (
                'id' => 389,
                'forum_id' => 45,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            240 =>
            array (
                'id' => 390,
                'forum_id' => 45,
                'group_id' => 15,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            241 =>
            array (
                'id' => 391,
                'forum_id' => 45,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            242 =>
            array (
                'id' => 392,
                'forum_id' => 45,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            243 =>
            array (
                'id' => 393,
                'forum_id' => 45,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            244 =>
            array (
                'id' => 394,
                'forum_id' => 46,
                'group_id' => 1,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            245 =>
            array (
                'id' => 395,
                'forum_id' => 46,
                'group_id' => 2,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            246 =>
            array (
                'id' => 396,
                'forum_id' => 46,
                'group_id' => 3,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            247 =>
            array (
                'id' => 397,
                'forum_id' => 46,
                'group_id' => 4,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            248 =>
            array (
                'id' => 398,
                'forum_id' => 46,
                'group_id' => 5,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            249 =>
            array (
                'id' => 399,
                'forum_id' => 46,
                'group_id' => 6,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            250 =>
            array (
                'id' => 400,
                'forum_id' => 46,
                'group_id' => 7,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            251 =>
            array (
                'id' => 401,
                'forum_id' => 46,
                'group_id' => 8,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            252 =>
            array (
                'id' => 402,
                'forum_id' => 46,
                'group_id' => 9,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            253 =>
            array (
                'id' => 403,
                'forum_id' => 46,
                'group_id' => 10,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            254 =>
            array (
                'id' => 404,
                'forum_id' => 46,
                'group_id' => 11,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            255 =>
            array (
                'id' => 405,
                'forum_id' => 46,
                'group_id' => 12,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            256 =>
            array (
                'id' => 406,
                'forum_id' => 46,
                'group_id' => 13,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            257 =>
            array (
                'id' => 407,
                'forum_id' => 46,
                'group_id' => 14,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            258 =>
            array (
                'id' => 408,
                'forum_id' => 46,
                'group_id' => 15,
                'show_forum' => 0,
                'read_topic' => 0,
                'reply_topic' => 0,
                'start_topic' => 0,
                'upload' => 0,
                'download' => 0,
            ),
            259 =>
            array (
                'id' => 409,
                'forum_id' => 46,
                'group_id' => 16,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            260 =>
            array (
                'id' => 410,
                'forum_id' => 46,
                'group_id' => 17,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
            261 =>
            array (
                'id' => 411,
                'forum_id' => 46,
                'group_id' => 18,
                'show_forum' => 1,
                'read_topic' => 1,
                'reply_topic' => 1,
                'start_topic' => 1,
                'upload' => 1,
                'download' => 1,
            ),
        ));
    }
}
