<?php

beforeEach(function (): void {
    $this->subject = new \App\Http\Requests\Staff\RejectApplicationRequest();
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'deny' => 'required',
    ], $actual);
});

// test cases...
