<?php

beforeEach(function (): void {
    $this->subject = new \App\Http\Requests\Staff\StoreUnbanRequest();
});

test('authorize', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->authorize();

    $this->assertTrue($actual);
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'owned_by' => [
        ],
        'unban_reason' => [
            'required',
            'string',
            'max:65536',
        ],
        'group_id' => [
            'required',
            'integer',
            'exists:groups,id',
        ],
    ], $actual);
});

// test cases...
