<?php

beforeEach(function (): void {
    $this->subject = new \App\Http\Requests\Staff\StoreBonExchangeRequest();
});

test('authorize', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->authorize();

    $this->assertTrue($actual);
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'description' => 'required|string',
        'value'       => 'required|numeric',
        'cost'        => 'required|numeric',
        'type'        => 'required|string|in:upload,download,personal_freeleech,invite|exclude',
    ], $actual);
});

// test cases...
