<?php

beforeEach(function (): void {
    $this->subject = new \App\Http\Requests\Staff\StoreWatchedUserRequest();
});

test('authorize', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->authorize();

    $this->assertTrue($actual);
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'message' => 'required|string|min:3',
    ], $actual);
});

// test cases...
