<?php

beforeEach(function (): void {
    $this->subject = new \App\Http\Requests\StorePoll();
});

test('authorize', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->authorize();

    $this->assertTrue($actual);
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'title'     => 'required|min:10',
        'options.*' => 'filled',
        'options'   => 'min:2',
    ], $actual);
});

test('messages', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->messages();

    $this->assertEquals([
        'options.*.filled' => 'You must fill in all options fields',
    ], $actual);
});

// test cases...
