<?php

beforeEach(function (): void {
    $this->subject = new \App\Http\Requests\StorePollVoteRequest();
});

test('authorize', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->authorize();

    $this->assertTrue($actual);
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'options' => [
            'required',
            'array',
            'min:1',
        ],
        'options.*' => [
            'integer',
        ],
    ], $actual);
});

test('messages', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->messages();

    $this->assertEquals([
        'options.required' => 'You must select an answer',
    ], $actual);
});

// test cases...
