<?php

beforeEach(function (): void {
    $this->subject = new \App\Http\Requests\StoreGiftRequest();
});

test('authorize', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->authorize();

    $this->assertTrue($actual);
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'to_username' => [
            'required',
            'exists:users,username',
        ],
        'bonus_points' => [
            'required',
            'numeric',
            'min:1',
        ],
        'bonus_message' => [
            'required',
            'string',
        ],
    ], $actual);
});

test('messages', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->messages();

    $this->assertEquals([
        'to_username.not_in' => 'You cannot gift yourself',
    ], $actual);
});

// test cases...
