<?php
/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

use App\Http\Requests\User\StorePostTipRequest;

beforeEach(function (): void {
    $this->subject = new StorePostTipRequest();
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'torrent' => [
            'bail',
            'prohibits:post',
            'required_without:post',
            'exists:torrents,id',
        ],
        'post' => [
            'bail',
            'prohibits:torrent',
            'required_without:torrent',
            'exists:posts,id',
        ],
        'tip' => [
            'required',
            'numeric',
            'min:1',
        ],
    ], $actual);
});

test('messages', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->messages();

    expect($actual)->toEqual([]);
});
