<?php

beforeEach(function (): void {
    $this->subject = new \App\Http\Requests\UpdateTorrentRequest();
});

test('authorize', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->authorize();

    $this->assertTrue($actual);
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'name' => [
            'required',
            'max:255',
        ],
        'description' => [
            'required',
            'max:4294967296',
        ],
        'mediainfo' => [
            'nullable',
            'sometimes',
            'max:4294967296',
        ],
        'bdinfo' => [
            'nullable',
            'sometimes',
            'max:4294967296',
        ],
        'category_id' => [
            'required',
            'exists:categories,id',
        ],
        'type_id' => [
            'required',
            'exists:types,id',
        ],
        'resolution_id' => [
            'exists:resolutions,id',
        ],
        'region_id' => [
            'nullable',
            'exists:regions,id',
        ],
        'distributor_id' => [
            'nullable',
            'exists:distributors,id',
        ],
        'imdb' => [
            'required',
            'numeric',
        ],
        'tvdb' => [
            'required',
            'numeric',
        ],
        'tmdb' => [
            'required',
            'numeric',
        ],
        'mal' => [
            'required',
            'numeric',
        ],
        'igdb' => [
            'required',
            'numeric',
        ],
        'season_number' => [
            'numeric',
        ],
        'episode_number' => [
            'numeric',
        ],
        'anon' => [
            'required',
            'boolean',
        ],
        'stream' => [
            'required',
            'boolean',
        ],
        'sd' => [
            'required',
            'boolean',
        ],
        'personal_release' => [
            'required',
            'boolean',
        ],
        'internal' => [
            'sometimes',
            'boolean',
        ],
        'free' => [
            'sometimes',
            'between:0,100',
        ],
        'refundable' => [
            'sometimes',
            'boolean',
        ],
    ], $actual);
});

// test cases...
