<?php

beforeEach(function (): void {
    $this->subject = new \App\Http\Requests\UpdateSubtitleRequest();
});

test('authorize', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->authorize();

    $this->assertTrue($actual);
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'language_id' => [
            'required',
        ],
        'note' => [
            'required',
            'max:65535',
        ],
        'anon' => [
            'required',
            'boolean',
        ],
    ], $actual);
});

// test cases...
