<?php

namespace Tests\Todo\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\VoteOnPoll
 */
class VoteOnPollTest extends TestCase
{
    /** @var \App\Http\Requests\VoteOnPoll */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\VoteOnPoll();
    }

    public function testAuthorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    public function testRules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertEquals([], $actual);
    }

    public function testMessages()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->messages();

        $this->assertEquals([], $actual);
    }

    // test cases...
}
