<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'articles'      => 'Artikler',
    'meta-articles' => 'Artikler og nyheder om tracker og samfundet',
    'published-at'  => 'Udgivet på',
    'read-more'     => 'Læs mere',
];
