<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'attemptsRemaining'          => 'Forsøg tilbageværende | Forsøg tilbageværende',
    'email'                      => 'E-mail',
    'exceededTitle'              => 'Verifikationsforsøg overskredet',
    'failed'                     => 'Disse legitimationsoplysninger svarer ikke til vores poster.',
    'inputAlt1'                  => 'Kodeindgang 1',
    'inputAlt2'                  => 'Kodeindgang 2',
    'inputAlt3'                  => 'Kodeindgang 3',
    'inputAlt4'                  => 'Kodeindgang 4',
    'lockedUntil'                => 'Konto låst indtil:',
    'login'                      => 'Log på',
    'login-now-on'               => 'Log ind nu',
    'logout'                     => 'Log ud',
    'lost-password'              => 'Glemt din adgangskode?',
    'lost-username'              => 'Glemt dit brugernavn?',
    'missingCode'                => 'Fik ikke bekræftelseskode?',
    'need-invite'                => 'Åben registrering er deaktiveret, og du skal bruge en invitation til at få adgang!',
    'no-a-member'                => 'Ikke medlem endnu? Tilmelding på mindre end 30s.',
    'password'                   => 'Adgangskode',
    'recover-my-password'        => 'Gendan min adgangskode',
    'remember-me'                => 'Husk mig',
    'returnButton'               => 'Vende hjem',
    'signup'                     => 'Tilmelde',
    'subtitle'                   => 'Verifikation kræves',
    'throttle'                   => 'For mange login forsøg. Prøv venligst igen i :seconds sekunder.',
    'title'                      => '2-trins verifikation',
    'titleFailed'                => 'Bekræftelsen mislykkedes',
    'titlePassed'                => 'Gode ​​nyheder alle!',
    'tryAgainIn'                 => 'Prøv igen i',
    'unlock'                     => 'Lås',
    'user-icon'                  => 'Brugerikon',
    'username'                   => 'Brugernavn',
    'verificationEmailButton'    => 'Verificer nu',
    'verificationEmailGreeting'  => 'Hej :username',
    'verificationEmailMessage'   => 'Din konto 2-trins verifikationskode er:',
    'verificationEmailSentMsg'   => 'Bekræftelse Email Sendt!',
    'verificationEmailSubject'   => 'Verifikation kræves',
    'verificationEmailSuccess'   => 'Succes!',
    'verificationLockedMessage'  => 'Konto låst!',
    'verificationLockedTitle'    => 'Doh!',
    'verificationModalConfBtn'   => 'Okay',
    'verificationWarningMessage' => 'Dette er dit sidste forsøg, før din konto låser for :hours timer.',
    'verificationWarningTitle'   => 'Advarsel!',
    'verifyButton'               => 'Verificere',
];
