<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'activate-account' => 'Aktivér konto',
    'ban-reason'       => 'Grund',
    'banned-footer'    => 'Det er hvad du får for ikke at følge reglerne',
    'banned-header'    => 'Du er blevet bandlyst',
    'bug-description'  => 'Problem',
    'bug-footer'       => 'Fix That Shit',
    'bug-header'       => 'Ny fejlrapport fra',
    'bug-priority'     => 'Prioritet',
    'bug-title'        => 'Fejltitel',
    'contact-header'   => 'Ny kontakt mail fra',
    'contact-message'  => 'Besked',
    'contact-name'     => 'Navn',
    'invite-header'    => 'Invitation til',
    'invite-invited'   => 'Du er blevet inviteret til',
    'invite-message'   => 'Besked',
    'invite-signup'    => 'Tilmeld dig nu',
    'newreply-header'  => 'Der er nyt svar i dit emne',
    'newreply-message' => 'Besked',
    'newreply-replied' => 'Har svaret på dit emne',
    'newreply-view'    => 'Se det nu',
    'register-code'    => 'For at afslutte din kontoaktivering klik på knappen nedenfor',
    'register-footer'  => 'Hvis knappen ovenfor ikke virker, skal du kopiere og indsætte webadressen i din browsers adresselinje',
    'register-header'  => 'Hej! Tak for at tilmelde dig',
    'report-comment'   => 'Kommentar',
    'report-email'     => 'E-mail',
    'report-header'    => 'Hej Admin, Der er rapporteret et link',
    'report-link'      => 'Link',
    'report-link-hash' => 'Faktisk link',
    'unban-footer'     => 'Velkommen tilbage!',
    'unban-header'     => 'Du har været forbudt',
    'unban-reason'     => 'Grund',
];
