<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'actions' => [
        'cancel'  => 'Отказ',
        'confirm' => 'Запазете нов ключ',
        'edit'    => 'редактиране',
        'save'    => 'Запазване!',
    ],
    'file'   => 'досие',
    'header' => [
        'actions' => 'мерки',
        'key'     => 'ключ',
        'value'   => 'стойност',
    ],
    'info_choose' => 'Изберете файл, за да започнете редактирането',
    'path'        => 'път',
    'sure'        => 'Сигурен ли си?',
    'title'       => 'Конфигурационен мениджър',
];
