<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AchievementsController
 */
class AchievementsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('achievements.index'));

        $response->assertOk();
        $response->assertViewIs('achievement.index');
        $response->assertViewHas('route');
        $response->assertViewHas('user');
        $response->assertViewHas('achievements');
        $response->assertViewHas('pending');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('achievements.show', ['username' => $username]));

        $response->assertOk();
        $response->assertViewIs('achievement.show');
        $response->assertViewHas('route');
        $response->assertViewHas('user');
        $response->assertViewHas('achievements');

        // TODO: perform additional assertions
    }

    // test cases...
}
