<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AnnounceController
 */
class AnnounceControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function announce_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('announce', ['passkey' => $passkey]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
