<?php
/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

use App\Models\Article;
use App\Models\User;

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $articles = Article::factory()->times(3)->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('articles.index'));

    $response->assertOk();
    $response->assertViewIs('article.index');
    $response->assertViewHas('articles', $articles);

    // TODO: perform additional assertions
});

test('show returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $article = Article::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('articles.show', [$article]));

    $response->assertOk();
    $response->assertViewIs('article.show');
    $response->assertViewHas('article', $article);

    // TODO: perform additional assertions
});

// test cases...
