<?php
/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

use App\Models\Forum;
use App\Models\User;

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $forums = Forum::factory()->times(3)->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('forums.index'));

    $response->assertOk();
    $response->assertViewIs('forum.index');
    $response->assertViewHas('categories');
    $response->assertViewHas('num_posts');
    $response->assertViewHas('num_forums');
    $response->assertViewHas('num_topics');

    // TODO: perform additional assertions
});

test('show returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $forum = Forum::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('forums.show', ['id' => $forum->id]));

    $response->assertOk();
    $response->assertViewIs('forum.forum_topic.index');
    $response->assertViewHas('forum', $forum);

    // TODO: perform additional assertions
});

// test cases...
