<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\GraveyardController
 */
class GraveyardControllerTest extends TestCase
{
    /** @test */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $graveyard = \App\Models\Graveyard::factory()->create();

        $response = $this->delete(route('graveyard.destroy', ['id' => $graveyard->id]));

        $response->assertOk();
        $this->assertDeleted($graveyard);

        // TODO: perform additional assertions
    }

    /** @test */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('graveyard.index'));

        $response->assertOk();
        $response->assertViewIs('graveyard.index');

        // TODO: perform additional assertions
    }

    /** @test */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $torrent = \App\Models\Torrent::factory()->create();
        $graveyard = \App\Models\Graveyard::factory()->create();

        $response = $this->post(route('graveyard.store', ['id' => $graveyard->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
