<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\HomeController
 */
class HomeControllerTest extends TestCase
{


    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

$user = factory(\App\Models\User::class)->create();

$response = $this->actingAs($user)->get(route('home.index'));

$response->assertOk();
$response->assertViewIs('home.index');
$response->assertViewHas('user');
$response->assertViewHas('personal_freeleech');
$response->assertViewHas('users');
$response->assertViewHas('groups');
$response->assertViewHas('articles');
$response->assertViewHas('newest');
$response->assertViewHas('seeded');
$response->assertViewHas('dying');
$response->assertViewHas('leeched');
$response->assertViewHas('dead');
$response->assertViewHas('topics');
$response->assertViewHas('posts');
$response->assertViewHas('featured');
$response->assertViewHas('poll');
$response->assertViewHas('uploaders');
$response->assertViewHas('past_uploaders');
$response->assertViewHas('freeleech_tokens');
$response->assertViewHas('bookmarks');

        // TODO: perform additional assertions
    }

    // test cases...
}
