<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MissingController
 */
class MissingControllerTest extends TestCase
{
    /** @test */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('missing.index'));

        $response->assertOk();
        $response->assertViewIs('missing.index');

        // TODO: perform additional assertions
    }

    // test cases...
}
