<?php



test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get(route('missing.index'));

    $response->assertOk();
    $response->assertViewIs('missing.index');

    // TODO: perform additional assertions
});

// test cases...
