<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\PlaylistController
 */
class PlaylistControllerTest extends TestCase
{
    /** @test */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('playlists.create'));

        $response->assertOk();
        $response->assertViewIs('playlist.create');

        // TODO: perform additional assertions
    }

    /** @test */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $playlist = \App\Models\Playlist::factory()->create();

        $response = $this->delete(route('playlists.destroy', ['id' => $playlist->id]));

        $response->assertOk();
        $this->assertDeleted($playlist);

        // TODO: perform additional assertions
    }

    /** @test */
    public function download_playlist_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $playlist = \App\Models\Playlist::factory()->create();
        $torrent = \App\Models\Torrent::factory()->create();
        $playlistTorrents = \App\Models\PlaylistTorrent::factory()->times(3)->create();

        $response = $this->get(route('playlists.download', ['id' => $playlist->id]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /** @test */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $playlist = \App\Models\Playlist::factory()->create();

        $response = $this->get(route('playlists.edit', ['id' => $playlist->id]));

        $response->assertOk();
        $response->assertViewIs('playlist.edit');
        $response->assertViewHas('playlist', $playlist);

        // TODO: perform additional assertions
    }

    /** @test */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $playlists = \App\Models\Playlist::factory()->times(3)->create();

        $response = $this->get(route('playlists.index'));

        $response->assertOk();
        $response->assertViewIs('playlist.index');
        $response->assertViewHas('playlists', $playlists);

        // TODO: perform additional assertions
    }

    /** @test */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $playlist = \App\Models\Playlist::factory()->create();
        $playlistTorrent = \App\Models\PlaylistTorrent::factory()->create();
        $torrent = \App\Models\Torrent::factory()->create();
        $tv = \App\Models\Tv::factory()->create();
        $movie = \App\Models\Movie::factory()->create();
        $playlistTorrents = \App\Models\PlaylistTorrent::factory()->times(3)->create();

        $response = $this->get(route('playlists.show', ['id' => $playlist->id]));

        $response->assertOk();
        $response->assertViewIs('playlist.show');
        $response->assertViewHas('playlist', $playlist);
        $response->assertViewHas('meta');
        $response->assertViewHas('torrents');

        // TODO: perform additional assertions
    }

    /** @test */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('playlists.store'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /** @test */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $playlist = \App\Models\Playlist::factory()->create();

        $response = $this->patch(route('playlists.update', ['id' => $playlist->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
