<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SeedboxController
 */
class SeedboxControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $seedbox = \App\Models\Seedbox::factory()->create();
        $seedboxes = \App\Models\Seedbox::factory()->times(3)->create();

        $response = $this->get(route('seedboxes.index', ['username' => $seedbox->username]));

        $response->assertOk();
        $response->assertViewIs('seedbox.index');
        $response->assertViewHas('user', $user);
        $response->assertViewHas('seedboxes', $seedboxes);

        // TODO: perform additional assertions
    }

    // test cases...
}
