<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\TicketAttachmentController
 */
class TicketAttachmentControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function download_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $ticketAttachment = \App\Models\TicketAttachment::factory()->create();

        $response = $this->post(route('tickets.attachment.download', ['attachment' => $ticketAttachment->attachment]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
