<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\TopicController
 */
class TopicControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function add_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $forum = \App\Models\Forum::factory()->create();
        $topic = \App\Models\Topic::factory()->create();

        $response = $this->get(route('forum_new_topic_form', ['id' => $topic->id]));

        $response->assertOk();
        $response->assertViewIs('forum.new_topic');
        $response->assertViewHas('forum', $forum);
        $response->assertViewHas('category');
        $response->assertViewHas('title');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function close_topic_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = \App\Models\Topic::factory()->create();

        $response = $this->post(route('forum_close', ['id' => $topic->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_topic_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = \App\Models\Topic::factory()->create();

        $response = $this->delete(route('forum_delete_topic', ['id' => $topic->id]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = \App\Models\Topic::factory()->create();
        $forums = \App\Models\Forum::factory()->times(3)->create();

        $response = $this->get(route('forum_edit_topic_form', ['id' => $topic->id]));

        $response->assertOk();
        $response->assertViewIs('forum.edit_topic');
        $response->assertViewHas('topic', $topic);
        $response->assertViewHas('categories');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_topic_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = \App\Models\Topic::factory()->create();

        $response = $this->post(route('forum_edit_topic', ['id' => $topic->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function new_topic_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $forum = \App\Models\Forum::factory()->create();
        $topic = \App\Models\Topic::factory()->create();

        $response = $this->post(route('forum_new_topic', ['id' => $topic->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function open_topic_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = \App\Models\Topic::factory()->create();

        $response = $this->post(route('forum_open', ['id' => $topic->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function pin_topic_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = \App\Models\Topic::factory()->create();

        $response = $this->post(route('forum_pin_topic', ['id' => $topic->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function topic_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = \App\Models\Topic::factory()->create();
        $forum = \App\Models\Forum::factory()->create();
        $post = \App\Models\Post::factory()->create();

        $response = $this->get(route('forum_topic', ['id' => $topic->id]));

        $response->assertOk();
        $response->assertViewIs('forum.topic');
        $response->assertViewHas('topic', $topic);
        $response->assertViewHas('forum', $forum);
        $response->assertViewHas('category');
        $response->assertViewHas('posts');
        $response->assertViewHas('firstPost');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function unpin_topic_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = \App\Models\Topic::factory()->create();

        $response = $this->post(route('forum_unpin_topic', ['id' => $topic->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
