<?php

uses(RefreshDatabase::class);

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $torrent = \App\Models\Torrent::factory()->create();
    $peers = \App\Models\Peer::factory()->times(3)->create();

    $response = $this->get(route('peers', ['id' => $id]));

    $response->assertOk();
    $response->assertViewIs('torrent.peers');
    $response->assertViewHas('torrent', $torrent);
    $response->assertViewHas('peers', $peers);

    // TODO: perform additional assertions
});

// test cases...
