<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\WarningController
 */
class WarningControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function deactivate_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $warning = \App\Models\Warning::factory()->create();

        $response = $this->post(route('deactivateWarning', ['id' => $warning->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function deactivate_all_warnings_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $warning = \App\Models\Warning::factory()->create();
        $warnings = \App\Models\Warning::factory()->times(3)->create();

        $response = $this->post(route('massDeactivateWarnings', ['username' => $warning->username]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_all_warnings_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $warning = \App\Models\Warning::factory()->create();
        $warnings = \App\Models\Warning::factory()->times(3)->create();

        $response = $this->delete(route('massDeleteWarnings', ['username' => $warning->username]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_warning_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $warning = \App\Models\Warning::factory()->create();

        $response = $this->delete(route('deleteWarning', ['id' => $warning->id]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function restore_warning_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $warning = \App\Models\Warning::factory()->create();

        $response = $this->post(route('restoreWarning', ['id' => $warning->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $warning = \App\Models\Warning::factory()->create();
        $warnings = \App\Models\Warning::factory()->times(3)->create();

        $response = $this->get(route('warnings.show', ['username' => $warning->username]));

        $response->assertOk();
        $response->assertViewIs('user.warninglog');
        $response->assertViewHas('warnings', $warnings);
        $response->assertViewHas('warningcount');
        $response->assertViewHas('softDeletedWarnings');
        $response->assertViewHas('softDeletedWarningCount');
        $response->assertViewHas('user', $user);

        // TODO: perform additional assertions
    }

    // test cases...
}
