<?php

namespace Tests\Unit\Console\Commands;

use Tests\TestCase;

/**
 * @see \App\Console\Commands\FetchReleaseYears
 */
class FetchReleaseYearsTest extends TestCase
{
    /**
     * @test
     */
    public function it_runs_successfully()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $this->artisan('fetch:release_years')
            ->expectsOutput('Torrent Release Year Command Complete')
            ->assertExitCode(0)
            ->run();
    }
}
