<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'articles'      => 'Články',
    'meta-articles' => 'Články a zprávy o trackeru a komunitě',
    'published-at'  => 'Publikováno v',
    'read-more'     => 'Přečtěte si více',
];
