<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'actions'                        => 'Akce',
    'backup'                         => 'Zálohování',
    'backup_doesnt_exist'            => 'Záložní soubor neexistuje.',
    'create_a_new_backup'            => 'Vytvořte novou zálohu',
    'create_confirmation_message'    => 'Obnovení stránky za 3 sekundy.',
    'create_confirmation_title'      => 'Zálohování dokončeno',
    'create_error_message'           => 'Nelze vytvořit záložní soubor.',
    'create_error_title'             => 'Chyba zálohování',
    'create_warning_message'         => 'Vaše záloha možná nebyla vytvořena. Pro podrobnosti prosím zkontrolujte soubory protokolu.',
    'create_warning_title'           => 'Neznámá chyba',
    'date'                           => 'datum',
    'delete'                         => 'Vymazat',
    'delete_cancel_message'          => 'Soubor zálohy nebyl odstraněn.',
    'delete_cancel_title'            => 'To je v pořádku',
    'delete_confirm'                 => 'Jste si jisti, že chcete vymazat tento soubor zálohy?',
    'delete_confirmation_message'    => 'Záložní soubor byl smazán.',
    'delete_confirmation_title'      => 'Hotovo',
    'delete_error_message'           => 'Soubor zálohy nebyl odstraněn.',
    'delete_error_title'             => 'Chyba',
    'download'                       => 'Stažení',
    'existing_backups'               => 'Existující zálohy',
    'file_size'                      => 'Velikost souboru',
    'location'                       => 'Umístění',
    'manager'                        => 'Manažer',
    'no_disks_configured'            => 'Žádné záložní disky nakonfigurované v souboru config / backup.php',
    'only_local_downloads_supported' => 'Jsou podporovány pouze stahování z lokálního souborového systému.',
];
