<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'bug-report'             => 'Chybová zpráva',
    'bug-report-description' => 'Nahlásit chybu webu',
    'enter-description'      => 'Popište problém co nejlépe',
    'enter-email'            => 'Zadejte svůj e-mail',
    'enter-title'            => 'Zvolte správný název',
    'enter-username'         => 'Zadejte své uživatelské jméno',
    'high'                   => 'Vysoký',
    'low'                    => 'Nízký',
    'priority'               => 'Přednost',
    'priority-description'   => 'Zvolte pouze velmi vysokou hodnotu, pokud je chyba opravdu problémem při používání webu.',
    'very-high'              => 'Velmi vysoko',
];
