<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'actions' => [
        'cancel'  => 'zrušení',
        'confirm' => 'Uložit nový klíč',
        'edit'    => 'Upravit',
        'save'    => 'Uložit!',
    ],
    'file'   => 'Soubor',
    'header' => [
        'actions' => 'Akce',
        'key'     => 'Klíč',
        'value'   => 'Hodnota',
    ],
    'info_choose' => 'Vyberte soubor, který chcete zahájit úpravu',
    'path'        => 'Cesta',
    'sure'        => 'Jsi si jistá?',
    'title'       => 'Správce konfigurace',
];
