<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'date'             => 'datum',
    'delete'           => 'Vymazat',
    'delete-all'       => 'Smazat všechna oznámení',
    'mark-all-read'    => 'označit vše jako přečtené',
    'mark-read'        => 'Označit jako přečtené',
    'message'          => 'Zpráva',
    'no-notifications' => 'Nebyly nalezeny žádná oznámení',
    'notifications'    => 'Oznámení',
    'read'             => 'Číst',
    'title'            => 'Titul',
];
