<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'create'        => 'Vytvořit',
    'delete'        => 'Vymazat',
    'enter-subject' => 'Zadejte předmět',
    'from'          => 'Z',
    'inbox'         => 'Doručená pošta',
    'mark-all-read' => 'Označte všechny zprávy jako přečtené',
    'message'       => 'Zpráva',
    'messages'      => 'Zprávy',
    'new'           => 'Nová zpráva',
    'outbox'        => 'Outbox',
    'private'       => 'Soukromé',
    'read'          => 'Číst',
    'received-at'   => 'Přijato na',
    'refresh'       => 'Obnovit',
    'reply'         => 'Odpověď',
    'search'        => 'Vyhledávání podle předmětu',
    'select'        => 'Vyberte uživatele',
    'send'          => 'Poslat',
    'sent'          => 'Odeslaná',
    'sent-at'       => 'Odeslaná na',
    'subject'       => 'Předmět',
    'to'            => 'Na',
    'unread'        => 'Nepřečtený',
];
