<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'by-count'                => 'Spočítat',
    'by-volume'               => 'Podle hlasitosti',
    'group'                   => 'Skupina',
    'groups'                  => 'Skupiny',
    'nerd-stats'              => 'Nerd statistiky',
    'nerd-stats-desc'         => 'Všichni rádi statistiky. Zde je několik, které považujeme za důležité',
    'registration-date'       => 'Datum registrace',
    'request-fulfilled'       => 'Požadavek splněn',
    'request-not-fulfilled'   => 'Žádost nebyla splněna',
    'request-pending-aproval' => 'Požádejte o schválení',
    'select-category'         => 'Vyberte kategorii níže',
    'site-stats'              => 'Statistika stránek',
    'stats'                   => 'Statistiky',
    'stats-format'            => 'Všechny statistiky zobrazeny ve formátu 100 nejlepších',
    'top-bankers'             => 'Nejlepší bankéři',
    'top-bountied'            => 'Nejvyšší skála',
    'top-completed'           => 'Nejlépe dokončeno',
    'top-dead'                => 'Top mrtvý',
    'top-downloaded'          => 'Nejlépe stažené torrenty',
    'top-downloaders'         => 'Nejlépe stahovatelé',
    'top-dying'               => 'Nejlépe umírá',
    'top-leeched'             => 'Horní pruh',
    'top-leechers'            => 'Top leechers',
    'top-seeded'              => 'Nejlépe nasazená',
    'top-seeders'             => 'Nejvýkonnější secí stroje',
    'top-seedsize'            => 'Nejvyšší počet semen',
    'top-seedtime'            => 'Nejvyšší doba vysazení',
    'top-uploaders'           => 'Nejčastěji se nahráli',
    'total-download'          => 'Celkové stahování',
    'total-torrents'          => 'Celkem torrentů',
    'total-traffic'           => 'Celková návštěvnost',
    'total-upload'            => 'Celkové nahrání',
    'users-in-group'          => 'Uživatelé ve skupině',
    'users-per-group'         => 'Uživatelé v každé skupině',
];
