<?php

uses(RefreshDatabase::class);

test('activate returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $userActivation = \App\Models\UserActivation::factory()->create();

    $response = $this->get(route('activate', ['token' => $token]));

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
