<?php

uses(RefreshDatabase::class);

test('send username reminder returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();

    $response = $this->post(route('username.email'), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('show forgot username form returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get(route('username.request'));

    $response->assertOk();
    $response->assertViewIs('auth.username');

    // TODO: perform additional assertions
});

// test cases...
