<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'actions' => [
        'cancel'  => 'Stornieren',
        'confirm' => 'Speichere neuen Schlüssel',
        'edit'    => 'Bearbeiten',
        'save'    => 'Sparen!',
    ],
    'file'   => 'Datei',
    'header' => [
        'actions' => 'Aktionen',
        'key'     => 'Schlüssel',
        'value'   => 'Wert',
    ],
    'info_choose' => 'Wählen Sie eine Datei, um mit der Bearbeitung zu beginnen',
    'path'        => 'Pfad',
    'sure'        => 'Bist du sicher?',
    'title'       => 'Konfigurationsmanager',
];
