<?php

namespace Tests\Feature\Http\Controllers\MediaHub;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MediaHub\CollectionController
 */
class CollectionControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('mediahub.collections.index'));

        $response->assertOk();
        $response->assertViewIs('mediahub.collection.index');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $collection = \App\Models\Collection::factory()->create();

        $response = $this->get(route('mediahub.collections.show', ['id' => $collection->id]));

        $response->assertOk();
        $response->assertViewIs('mediahub.collection.show');
        $response->assertViewHas('collection', $collection);

        // TODO: perform additional assertions
    }

    // test cases...
}
