<?php

namespace Tests\Feature\Http\Controllers\MediaHub;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MediaHub\HomeController
 */
class HomeControllerTest extends TestCase
{
    /** @test */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('mediahub.index'));

        $response->assertOk();
        $response->assertViewIs('mediahub.index');
        $response->assertViewHas('tv');
        $response->assertViewHas('movies');
        $response->assertViewHas('collections');
        $response->assertViewHas('persons');
        $response->assertViewHas('genres');
        $response->assertViewHas('networks');
        $response->assertViewHas('companies');

        // TODO: perform additional assertions
    }

    // test cases...
}
