<?php

namespace Tests\Feature\Http\Controllers\MediaHub;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MediaHub\MovieController
 */
class MovieControllerTest extends TestCase
{
    /** @test */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('mediahub.movies.index'));

        $response->assertOk();
        $response->assertViewIs('mediahub.movie.index');

        // TODO: perform additional assertions
    }

    /** @test */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $personalFreeleech = \App\Models\PersonalFreeleech::factory()->create();
        $movie = \App\Models\Movie::factory()->create();

        $response = $this->get(route('mediahub.movies.show', ['id' => $movie->id]));

        $response->assertOk();
        $response->assertViewIs('mediahub.movie.show');
        $response->assertViewHas('movie', $movie);
        $response->assertViewHas('user');
        $response->assertViewHas('personal_freeleech');

        // TODO: perform additional assertions
    }

    // test cases...
}
