<?php

namespace Tests\Feature\Http\Controllers\MediaHub;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MediaHub\NetworkController
 */
class NetworkControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('mediahub.networks.index'));

        $response->assertOk();
        $response->assertViewIs('mediahub.network.index');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $network = \App\Models\Network::factory()->create();

        $response = $this->get(route('mediahub.networks.show', ['id' => $network->id]));

        $response->assertOk();
        $response->assertViewIs('mediahub.network.show');
        $response->assertViewHas('network', $network);
        $response->assertViewHas('shows');

        // TODO: perform additional assertions
    }

    // test cases...
}
