<?php

namespace Tests\Feature\Http\Controllers\MediaHub;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MediaHub\PersonController
 */
class PersonControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('mediahub.persons.index'));

        $response->assertOk();
        $response->assertViewIs('mediahub.person.index');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $person = \App\Models\Person::factory()->create();

        $response = $this->get(route('mediahub.persons.show', ['id' => $person->id]));

        $response->assertOk();
        $response->assertViewIs('mediahub.person.show');
        $response->assertViewHas('credits');
        $response->assertViewHas('details');

        // TODO: perform additional assertions
    }

    // test cases...
}
