<?php

namespace Tests\Feature\Http\Controllers\MediaHub;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MediaHub\TvShowController
 */
class TvShowControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('mediahub.shows.index'));

        $response->assertOk();
        $response->assertViewIs('mediahub.tv.index');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $tv = \App\Models\Tv::factory()->create();

        $response = $this->get(route('mediahub.shows.show', ['id' => $id]));

        $response->assertOk();
        $response->assertViewIs('mediahub.tv.show');
        $response->assertViewHas('show');

        // TODO: perform additional assertions
    }

    // test cases...
}
