<?php

use App\Models\Application;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

uses(TestCase::class);
uses(RefreshDatabase::class);

/**
 * @see \App\Http\Controllers\Staff\ApplicationController
 */
test('approve returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $application = Application::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->post(route('staff.applications.approve', ['id' => $application->id]), [
        // TODO: send request data
    ]);

    $response->assertRedirect(withErrors($v->errors()));

    // TODO: perform additional assertions
});

test('index returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.applications.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.application.index');
    $response->assertViewHas('applications');

    // TODO: perform additional assertions
});

test('reject returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $application = Application::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->post(route('staff.applications.reject', ['id' => $application->id]), [
        // TODO: send request data
    ]);

    $response->assertRedirect(withSuccess('Application Rejected'));

    // TODO: perform additional assertions
});

test('show returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $application = Application::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.applications.show', ['id' => $application->id]));

    $response->assertOk();
    $response->assertViewIs('Staff.application.show');
    $response->assertViewHas('application');

    // TODO: perform additional assertions
});
