<?php

namespace Tests\Todo\Feature\Http\Controllers\Staff;

use PHPUnit\Framework\Attributes\Test;
use App\Models\Audit;
use App\Models\User;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\AuditController
 */
class AuditControllerTest extends TestCase
{
    #[Test]
    public function destroy_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $audit = Audit::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->delete(route('staff.audits.destroy', ['audit' => $audit]));

        $response->assertRedirect(withSuccess('Audit Record Has Successfully Been Deleted'));
        $this->assertModelMissing($staff);

        // TODO: perform additional assertions
    }

    #[Test]
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('staff.audits.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.audit.index');
        $response->assertViewHas('audits');

        // TODO: perform additional assertions
    }

    // test cases...
}
