<?php

namespace Tests\Feature\Http\Controllers\Staff;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\FlushController
 */
class FlushControllerTest extends TestCase
{
    /**
     * @test
     */
    public function chat_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('staff.flush.chat'));

        $response->assertRedirect(withSuccess('Chatbox Has Been Flushed'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function peers_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('staff.flush.peers'));

        $response->assertRedirect(withSuccess('Ghost Peers Have Been Flushed'));

        // TODO: perform additional assertions
    }

    // test cases...
}
