<?php

namespace Tests\Todo\Feature\Http\Controllers\Staff;

use App\Models\User;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\FlushController
 */
class FlushControllerTest extends TestCase
{
    public function testChatReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('staff.flush.chat'));

        $response->assertRedirect(withSuccess('Chatbox Has Been Flushed'));

        // TODO: perform additional assertions
    }

    public function testPeersReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('staff.flush.peers'));

        $response->assertRedirect(withSuccess('Ghost Peers Have Been Flushed'));

        // TODO: perform additional assertions
    }

    // test cases...
}
