<?php

namespace Tests\Todo\Feature\Http\Controllers\Staff;

use App\Models\Forum;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\ForumController
 */
class ForumControllerTest extends TestCase
{
    use RefreshDatabase;

    public function testCreateReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('staff.forums.create'));

        $response->assertOk();
        $response->assertViewIs('Staff.forum.create');
        $response->assertViewHas('categories');
        $response->assertViewHas('groups');

        // TODO: perform additional assertions
    }

    public function testDestroyReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $forum = Forum::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->delete(route('staff.forums.destroy', ['id' => $forum->id]));

        $response->assertRedirect(withSuccess('Forum has been deleted successfully'));
        $this->assertDeleted($staff);

        // TODO: perform additional assertions
    }

    public function testEditReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $forum = Forum::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('staff.forums.edit', ['id' => $forum->id]));

        $response->assertOk();
        $response->assertViewIs('Staff.forum.edit');
        $response->assertViewHas('categories');
        $response->assertViewHas('groups');
        $response->assertViewHas('forum');

        // TODO: perform additional assertions
    }

    public function testIndexReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('staff.forums.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.forum.index');
        $response->assertViewHas('categories');

        // TODO: perform additional assertions
    }

    public function testStoreReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->post(route('staff.forums.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withSuccess('Forum has been created successfully'));

        // TODO: perform additional assertions
    }

    public function testUpdateReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $forum = Forum::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->post(route('staff.forums.update', ['id' => $forum->id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withSuccess('Forum has been edited successfully'));

        // TODO: perform additional assertions
    }

    // test cases...
}
