<?php

namespace Tests\Todo\Feature\Http\Controllers\Staff;

use PHPUnit\Framework\Attributes\Test;
use App\Models\Poll;
use App\Models\User;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\PollController
 */
final class PollControllerTest extends TestCase
{
    #[Test]
    public function create_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('staff.polls.create'));

        $response->assertOk();
        $response->assertViewIs('Staff.poll.create');

        // TODO: perform additional assertions
    }

    #[Test]
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('staff.polls.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.poll.index');
        $response->assertViewHas('polls');

        // TODO: perform additional assertions
    }

    #[Test]
    public function show_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $poll = Poll::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('staff.polls.show', ['poll' => $poll]));

        $response->assertOk();
        $response->assertViewIs('Staff.poll.show');
        $response->assertViewHas('poll');

        // TODO: perform additional assertions
    }

    #[Test]
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->post(route('staff.polls.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withSuccess('Your poll has been created.'));

        // TODO: perform additional assertions
    }

    #[Test]
    public function store_validates_with_a_form_request(): void
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Staff\PollController::class,
            'store',
            \App\Http\Requests\StorePoll::class
        );
    }

    // test cases...
}
