<?php

namespace Tests\Feature\Http\Controllers\Staff;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\ReportController
 */
class ReportControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('staff.reports.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.report.index');
        $response->assertViewHas('reports');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $report = factory(\App\Models\Report::class)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('staff.reports.show', ['id' => $report->id]));

        $response->assertOk();
        $response->assertViewIs('Staff.report.show');
        $response->assertViewHas('report');
        $response->assertViewHas('urls');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $report = factory(\App\Models\Report::class)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->post(route('staff.reports.update', ['id' => $report->id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withErrors('This Report Has Already Been Solved'));

        // TODO: perform additional assertions
    }

    // test cases...
}
