<?php

namespace Tests\Todo\Feature\Http\Controllers\Staff;

use PHPUnit\Framework\Attributes\Test;
use App\Models\Seedbox;
use App\Models\User;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\SeedboxController
 */
final class SeedboxControllerTest extends TestCase
{
    #[Test]
    public function destroy_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $seedbox = Seedbox::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->delete(route('staff.seedboxes.destroy', ['seedbox' => $seedbox]));

        $response->assertRedirect(withSuccess('Seedbox Record Has Successfully Been Deleted'));
        $this->assertModelMissing($staff);

        // TODO: perform additional assertions
    }

    #[Test]
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('staff.seedboxes.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.seedbox.index');
        $response->assertViewHas('seedboxes');

        // TODO: perform additional assertions
    }

    // test cases...
}
