<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'create'        => '创建',
    'delete'        => '删除',
    'enter-subject' => '输入主题',
    'from'          => '从',
    'inbox'         => '收件箱',
    'mark-all-read' => '将所有消息标记为已读',
    'message'       => '信息',
    'messages'      => '消息',
    'new'           => '新消息',
    'outbox'        => '发件箱',
    'private'       => '私人的',
    'read'          => '读',
    'received-at'   => '收到At',
    'refresh'       => '刷新',
    'reply'         => '回复',
    'search'        => '按主题搜索',
    'select'        => '选择一个用户',
    'send'          => '发送',
    'sent'          => '发送',
    'sent-at'       => '发送',
    'subject'       => '学科',
    'to'            => '至',
    'unread'        => '未读',
];
