<?php


/**
 * This file was automatically generated by iTranslate software.
 *
 * Created by HolluwaTosin360
 * Email: henryogunrinde@yahoo.com
 */

return [
    'by-count'                => '计数',
    'by-volume'               => '按体积',
    'group'                   => '组',
    'groups'                  => '组',
    'nerd-stats'              => '书呆子统计',
    'nerd-stats-desc'         => '我们都喜欢统计数据。这里有一些我们认为重要的',
    'registration-date'       => '注册日期',
    'request-fulfilled'       => '请求已完成',
    'request-not-fulfilled'   => '请求没有完成',
    'request-pending-aproval' => '申请待批准',
    'select-category'         => '请在下面选择一个类别',
    'site-stats'              => '网站统计信息',
    'stats'                   => '统计',
    'stats-format'            => '所有统计信息显示在前100格式',
    'top-bankers'             => '顶级银行家',
    'top-bountied'            => '顶级褒奖',
    'top-completed'           => '上面完成',
    'top-dead'                => '死了',
    'top-downloaded'          => '热门下载的种子',
    'top-downloaders'         => '顶级下载',
    'top-dying'               => '顶死',
    'top-leeched'             => '顶部榨汁',
    'top-leechers'            => '顶级吸血鬼',
    'top-seeded'              => '顶级种子',
    'top-seeders'             => '顶级播种机',
    'top-seedsize'            => '顶级种子',
    'top-seedtime'            => '顶级种子时间',
    'top-uploaders'           => '顶级上传者',
    'total-download'          => '总下载',
    'total-torrents'          => '总种子',
    'total-traffic'           => '总流量',
    'total-upload'            => '总上传',
    'users-in-group'          => '组中的用户',
    'users-per-group'         => '每组用户',
];
