<?php
/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

use App\Http\Controllers\Staff\ApplicationController;
use App\Http\Requests\Staff\ApproveApplicationRequest;
use App\Http\Requests\Staff\RejectApplicationRequest;
use App\Models\Application;
use App\Models\Group;
use App\Models\Scopes\ApprovedScope;
use App\Models\User;

beforeEach(function () {
    $this->staffUser = User::factory()->create([
        'group_id' => fn () => Group::factory()->create([
            'is_owner' => true,
            'is_admin' => true,
            'is_modo'  => true,
        ])->id,
    ]);
});

test('approve validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        ApplicationController::class,
        'approve',
        ApproveApplicationRequest::class
    );
});

test('approve returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $application = Application::factory()->create([
        'status' => Application::PENDING,
    ]);

    $response = $this->actingAs($this->staffUser)->post(route('staff.applications.approve', ['id' => $application->id]), [
        'status' => Application::APPROVED,
        'moderated_by' => $this->staffUser->id,
        'moderated_at' => now(),
    ]);
    $response->assertRedirect(route('staff.applications.index'));
    $response->assertSessionHas('success', 'Application Approved');
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $applications = Application::factory()->times(3)->create()
        ->withoutGlobalScope(ApprovedScope::class)
        ->with(['user', 'moderated', 'imageProofs', 'urlProofs'])
        ->latest()
        ->paginate(25);

    $response = $this->actingAs($this->staffUser)->get(route('staff.applications.index'));
    $response->assertOk();
    $response->assertViewIs('Staff.application.index');
    $response->assertViewHas('applications', $applications);

    // TODO: perform additional assertions
});

test('reject validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        ApplicationController::class,
        'reject',
        RejectApplicationRequest::class
    );
});

test('reject returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $application = Application::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->post(route('staff.applications.reject', ['id' => $application->id]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('show returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $application = Application::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.applications.show', ['id' => $application->id]));

    $response->assertOk();
    $response->assertViewIs('Staff.application.show');
    $response->assertViewHas('application', $application);

    // TODO: perform additional assertions
});

// test cases...
