<?php

namespace Tests\Feature\Http\Controllers\Staff;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\AuditController
 */
class AuditControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $audit = \App\Models\Audit::factory()->create();

        $response = $this->delete(route('staff.audits.destroy', ['id' => $audit->id]));

        $response->assertOk();
        $this->assertDeleted($staff.audit);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $audits = \App\Models\Audit::factory()->times(3)->create();

        $response = $this->get(route('staff.audits.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.audit.index');
        $response->assertViewHas('audits', $audits);

        // TODO: perform additional assertions
    }

    // test cases...
}
