<?php

namespace Tests\Feature\Http\Controllers\Staff;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\AuthenticationController
 */
class AuthenticationControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $failedLoginAttempts = \App\Models\FailedLoginAttempt::factory()->times(3)->create();

        $response = $this->get(route('staff.authentications.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.authentication.index');
        $response->assertViewHas('attempts');

        // TODO: perform additional assertions
    }

    // test cases...
}
