<?php

uses(RefreshDatabase::class);

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $failedLoginAttempts = \App\Models\FailedLoginAttempt::factory()->times(3)->create();

    $response = $this->get(route('staff.authentications.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.authentication.index');
    $response->assertViewHas('attempts');

    // TODO: perform additional assertions
});

// test cases...
