<?php

uses(RefreshDatabase::class);

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $bans = \App\Models\Ban::factory()->times(3)->create();

    $response = $this->get(route('staff.bans.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.ban.index');
    $response->assertViewHas('bans', $bans);

    // TODO: perform additional assertions
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();
    $ban = \App\Models\Ban::factory()->create();

    $response = $this->post(route('staff.bans.store', ['username' => $ban->username]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('store validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        \App\Http\Controllers\Staff\BanController::class,
        'store',
        \App\Http\Requests\Staff\StoreBanRequest::class
    );
});

test('update returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();
    $ban = \App\Models\Ban::factory()->create();

    $response = $this->post(route('staff.bans.update', ['username' => $ban->username]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('update validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        \App\Http\Controllers\Staff\BanController::class,
        'update',
        \App\Http\Requests\Staff\UpdateBanRequest::class
    );
});

// test cases...
