<?php

uses(RefreshDatabase::class);

test('create returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get(route('staff.blacklists.clients.create'));

    $response->assertOk();
    $response->assertViewIs('Staff.blacklist.clients.create');

    // TODO: perform additional assertions
});

test('destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $blacklistClient = \App\Models\BlacklistClient::factory()->create();

    $response = $this->delete(route('staff.blacklists.clients.destroy', ['id' => $blacklistClient->id]));

    $response->assertOk();
    $this->assertModelMissing($staff.blacklists.client);

    // TODO: perform additional assertions
});

test('edit returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $blacklistClient = \App\Models\BlacklistClient::factory()->create();

    $response = $this->get(route('staff.blacklists.clients.edit', ['id' => $blacklistClient->id]));

    $response->assertOk();
    $response->assertViewIs('Staff.blacklist.clients.edit');
    $response->assertViewHas('client');

    // TODO: perform additional assertions
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $blacklistClients = \App\Models\BlacklistClient::factory()->times(3)->create();

    $response = $this->get(route('staff.blacklists.clients.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.blacklist.clients.index');
    $response->assertViewHas('clients');

    // TODO: perform additional assertions
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->post(route('staff.blacklists.clients.store'), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('store validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        \App\Http\Controllers\Staff\BlacklistClientController::class,
        'store',
        \App\Http\Requests\Staff\StoreBlacklistClientRequest::class
    );
});

test('update returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $blacklistClient = \App\Models\BlacklistClient::factory()->create();

    $response = $this->patch(route('staff.blacklists.clients.update', ['id' => $blacklistClient->id]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('update validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        \App\Http\Controllers\Staff\BlacklistClientController::class,
        'update',
        \App\Http\Requests\Staff\UpdateBlacklistClientRequest::class
    );
});

// test cases...
