<?php
/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

use App\Http\Controllers\Staff\ChatStatusController;
use App\Http\Requests\Staff\StoreChatStatusRequest;
use App\Http\Requests\Staff\UpdateChatStatusRequest;
use App\Models\ChatStatus;
use App\Models\User;

test('create returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.statuses.create'));

    $response->assertOk();
    $response->assertViewIs('Staff.chat.status.create');

    // TODO: perform additional assertions
});

test('destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $chatStatus = ChatStatus::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->delete(route('staff.statuses.destroy', [$chatStatus]));

    $response->assertOk();
    $this->assertModelMissing($chatStatus);

    // TODO: perform additional assertions
});

test('edit returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $chatStatus = ChatStatus::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.statuses.edit', [$chatStatus]));

    $response->assertOk();
    $response->assertViewIs('Staff.chat.status.edit');
    $response->assertViewHas('chatstatus');

    // TODO: perform additional assertions
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $chatStatuses = ChatStatus::factory()->times(3)->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.statuses.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.chat.status.index');
    $response->assertViewHas('chatstatuses');

    // TODO: perform additional assertions
});

test('store validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        ChatStatusController::class,
        'store',
        StoreChatStatusRequest::class
    );
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->post(route('staff.statuses.store'), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('update validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        ChatStatusController::class,
        'update',
        UpdateChatStatusRequest::class
    );
});

test('update returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $chatStatus = ChatStatus::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->post(route('staff.statuses.update', [$chatStatus]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
