<?php

namespace Tests\Feature\Http\Controllers\Staff;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\CheaterController
 */
class CheaterControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $histories = \App\Models\History::factory()->times(3)->create();

        $response = $this->get(route('staff.cheaters.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.cheater.index');
        $response->assertViewHas('cheaters');

        // TODO: perform additional assertions
    }

    // test cases...
}
