<?php

uses(RefreshDatabase::class);

test('destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->delete(route('staff.cheated_torrents.destroy', ['id' => $id]));

    $response->assertOk();
    $this->assertModelMissing($staff.cheatedTorrent);

    // TODO: perform additional assertions
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $torrents = \App\Models\Torrent::factory()->times(3)->create();

    $response = $this->get(route('staff.cheated_torrents.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.cheated_torrent.index');
    $response->assertViewHas('torrents', $torrents);

    // TODO: perform additional assertions
});

test('mass destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->delete(route('staff.cheated_torrents.massDestroy'));

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
