<?php

namespace Tests\Feature\Http\Controllers\Staff;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\ForumController
 */
class ForumControllerTest extends TestCase
{
    /** @test */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $forums = \App\Models\Forum::factory()->times(3)->create();
        $roles = \App\Models\Role::factory()->times(3)->create();

        $response = $this->get(route('staff.forums.create'));

        $response->assertOk();
        $response->assertViewIs('Staff.forum.create');
        $response->assertViewHas('categories');
        $response->assertViewHas('roles', $roles);

        // TODO: perform additional assertions
    }

    /** @test */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $forum = \App\Models\Forum::factory()->create();
        $privilege = \App\Models\Privilege::factory()->create();

        $response = $this->delete(route('staff.forums.destroy', ['id' => $forum->id]));

        $response->assertOk();
        $this->assertDeleted($staff.forum);

        // TODO: perform additional assertions
    }

    /** @test */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $forum = \App\Models\Forum::factory()->create();
        $forums = \App\Models\Forum::factory()->times(3)->create();
        $roles = \App\Models\Role::factory()->times(3)->create();

        $response = $this->get(route('staff.forums.edit', ['id' => $forum->id]));

        $response->assertOk();
        $response->assertViewIs('Staff.forum.edit');
        $response->assertViewHas('categories');
        $response->assertViewHas('roles', $roles);
        $response->assertViewHas('forum', $forum);

        // TODO: perform additional assertions
    }

    /** @test */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $forums = \App\Models\Forum::factory()->times(3)->create();

        $response = $this->get(route('staff.forums.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.forum.index');
        $response->assertViewHas('categories');

        // TODO: perform additional assertions
    }

    /** @test */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('staff.forums.store'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /** @test */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $forum = \App\Models\Forum::factory()->create();

        $response = $this->post(route('staff.forums.update', ['id' => $forum->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
