<?php
/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

use App\Models\User;

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.dashboard.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.dashboard.index');
    $response->assertViewHas('users');
    $response->assertViewHas('torrents');
    $response->assertViewHas('peers');
    $response->assertViewHas('reports');
    $response->assertViewHas('apps');
    $response->assertViewHas('certificate');
    $response->assertViewHas('uptime');
    $response->assertViewHas('ram');
    $response->assertViewHas('disk');
    $response->assertViewHas('avg');
    $response->assertViewHas('basic');
    $response->assertViewHas('file_permissions');

    // TODO: perform additional assertions
});

// test cases...
