<?php

namespace Tests\Feature\Http\Controllers\Staff;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\HomeController
 */
class HomeControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('staff.dashboard.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.dashboard.index');
        $response->assertViewHas('users');
        $response->assertViewHas('torrents');
        $response->assertViewHas('peers');
        $response->assertViewHas('reports');
        $response->assertViewHas('apps');
        $response->assertViewHas('certificate');
        $response->assertViewHas('uptime');
        $response->assertViewHas('ram');
        $response->assertViewHas('disk');
        $response->assertViewHas('avg');
        $response->assertViewHas('basic');
        $response->assertViewHas('file_permissions');

        // TODO: perform additional assertions
    }

    // test cases...
}
