<?php

namespace Tests\Feature\Http\Controllers\Staff;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\InternalController
 */
class InternalControllerTest extends TestCase
{
    /** @test */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('staff.internals.create'));

        $response->assertOk();
        $response->assertViewIs('Staff.internals.create');

        // TODO: perform additional assertions
    }

    /** @test */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $internal = \App\Models\Internal::factory()->create();

        $response = $this->delete(route('staff.internals.destroy', ['id' => $internal->id]));

        $response->assertOk();
        $this->assertDeleted($staff.internal);

        // TODO: perform additional assertions
    }

    /** @test */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $internal = \App\Models\Internal::factory()->create();

        $response = $this->get(route('staff.internals.edit', ['id' => $internal->id]));

        $response->assertOk();
        $response->assertViewIs('Staff.internals.edit');
        $response->assertViewHas('internal', $internal);

        // TODO: perform additional assertions
    }

    /** @test */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $internals = \App\Models\Internal::factory()->times(3)->create();

        $response = $this->get(route('staff.internals.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.internals.index');
        $response->assertViewHas('internals', $internals);

        // TODO: perform additional assertions
    }

    /** @test */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('staff.internals.store'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /** @test */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $internal = \App\Models\Internal::factory()->create();

        $response = $this->post(route('staff.internals.update', ['id' => $internal->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
