<?php

uses(RefreshDatabase::class);

test('create returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.media_languages.create'));

    $response->assertOk();
    $response->assertViewIs('Staff.media_language.create');

    // TODO: perform additional assertions
});

test('destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $mediaLanguage = \App\Models\MediaLanguage::factory()->create();
    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->delete(route('staff.media_languages.destroy', [$mediaLanguage]));

    $response->assertOk();
    $this->assertModelMissing($mediaLanguage);

    // TODO: perform additional assertions
});

test('edit returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $mediaLanguage = \App\Models\MediaLanguage::factory()->create();
    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.media_languages.edit', [$mediaLanguage]));

    $response->assertOk();
    $response->assertViewIs('Staff.media_language.edit');
    $response->assertViewHas('media_language');

    // TODO: perform additional assertions
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $mediaLanguages = \App\Models\MediaLanguage::factory()->times(3)->create();
    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.media_languages.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.media_language.index');
    $response->assertViewHas('media_languages');

    // TODO: perform additional assertions
});

test('store validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        \App\Http\Controllers\Staff\MediaLanguageController::class,
        'store',
        \App\Http\Requests\Staff\StoreMediaLanguageRequest::class
    );
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->post(route('staff.media_languages.store'), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('update validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        \App\Http\Controllers\Staff\MediaLanguageController::class,
        'update',
        \App\Http\Requests\Staff\UpdateMediaLanguageRequest::class
    );
});

test('update returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $mediaLanguage = \App\Models\MediaLanguage::factory()->create();
    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->patch(route('staff.media_languages.update', [$mediaLanguage]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
