<?php
/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

use App\Http\Controllers\Staff\RegionController;
use App\Http\Requests\Staff\DestroyRegionRequest;
use App\Http\Requests\Staff\StoreRegionRequest;
use App\Http\Requests\Staff\UpdateRegionRequest;
use App\Models\Region;
use App\Models\User;

test('create returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.regions.create'));

    $response->assertOk();
    $response->assertViewIs('Staff.region.create');

    // TODO: perform additional assertions
});

test('destroy validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        RegionController::class,
        'destroy',
        DestroyRegionRequest::class
    );
});

test('destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $region = Region::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->delete(route('staff.regions.destroy', [$region]));

    $response->assertOk();
    $this->assertModelMissing($region);

    // TODO: perform additional assertions
});

test('edit returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $region = Region::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.regions.edit', [$region]));

    $response->assertOk();
    $response->assertViewIs('Staff.region.edit');
    $response->assertViewHas('region', $region);

    // TODO: perform additional assertions
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $regions = Region::factory()->times(3)->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.regions.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.region.index');
    $response->assertViewHas('regions', $regions);

    // TODO: perform additional assertions
});

test('store validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        RegionController::class,
        'store',
        StoreRegionRequest::class
    );
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->post(route('staff.regions.store'), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('update validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        RegionController::class,
        'update',
        UpdateRegionRequest::class
    );
});

test('update returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $region = Region::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->patch(route('staff.regions.update', [$region]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
