<?php

namespace Tests\Feature\Http\Controllers\Staff;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\SeedboxController
 */
class SeedboxControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $seedbox = \App\Models\Seedbox::factory()->create();

        $response = $this->delete(route('staff.seedboxes.destroy', ['id' => $seedbox->id]));

        $response->assertOk();
        $this->assertDeleted($staff.seedbox);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $seedboxes = \App\Models\Seedbox::factory()->times(3)->create();

        $response = $this->get(route('staff.seedboxes.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.seedbox.index');
        $response->assertViewHas('seedboxes', $seedboxes);

        // TODO: perform additional assertions
    }

    // test cases...
}
