<?php

uses(RefreshDatabase::class);

test('check version returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.'));

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
