<?php

namespace Tests\Feature\Http\Controllers\Staff;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Staff\WarningController
 */
class WarningControllerTest extends TestCase
{
    /** @test */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $warnings = \App\Models\Warning::factory()->times(3)->create();

        $response = $this->get(route('staff.warnings.index'));

        $response->assertOk();
        $response->assertViewIs('Staff.warning.index');
        $response->assertViewHas('warnings', $warnings);
        $response->assertViewHas('warningcount');

        // TODO: perform additional assertions
    }

    // test cases...
}
