<?php

uses(RefreshDatabase::class);

test('destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $watchlist = \App\Models\Watchlist::factory()->create();

    $response = $this->delete(route('staff.watchlist.destroy', ['id' => $watchlist->id]));

    $response->assertOk();
    $this->assertModelMissing($staff.watchlist);

    // TODO: perform additional assertions
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get(route('staff.watchlist.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.watchlist.index');

    // TODO: perform additional assertions
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $watchlist = \App\Models\Watchlist::factory()->create();

    $response = $this->post(route('staff.watchlist.store', ['id' => $watchlist->id]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('store validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        \App\Http\Controllers\Staff\WatchlistController::class,
        'store',
        \App\Http\Requests\Staff\StoreWatchedUserRequest::class
    );
});

// test cases...
