<?php

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

uses(TestCase::class);
uses(RefreshDatabase::class);

/**
 * @see \App\Http\Controllers\LanguageController
 */
test('back returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $language = Language::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('back', ['locale' => $language->locale]));

    $response->assertRedirect(withSuccess('Language Changed!'));

    // TODO: perform additional assertions
});
