<?php

namespace Tests\Todo\Feature\Http\Controllers;

use PHPUnit\Framework\Attributes\Test;
use App\Models\PlaylistTorrent;
use App\Models\User;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\PlaylistTorrentController
 */
final class PlaylistTorrentControllerTest extends TestCase
{
    #[Test]
    public function destroy_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $playlist_torrent = PlaylistTorrent::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->delete(route('playlist_torrents.destroy', ['playlistTorrent' => $playlist_torrent]));

        $response->assertRedirect(withSuccess('Torrent Has Successfully Been Detached From Your Playlist.'));
        $this->assertModelMissing($playlists);

        // TODO: perform additional assertions
    }

    #[Test]
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->post(route('playlist_torrents.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withErrors($v->errors()));

        // TODO: perform additional assertions
    }

    // test cases...
}
