<?php

namespace Tests\Todo\Feature\Http\Controllers;

use App\Models\Poll;
use App\Models\User;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\PollController
 */
class PollControllerTest extends TestCase
{
    public function testIndexReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('polls'));

        $response->assertOk();
        $response->assertViewIs('poll.latest');
        $response->assertViewHas('polls');

        // TODO: perform additional assertions
    }

    public function testResultReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $poll = Poll::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('poll_results', ['id' => $poll->id]));

        $response->assertOk();
        $response->assertViewIs('poll.result');

        // TODO: perform additional assertions
    }

    public function testShowReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $poll = Poll::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('poll', ['id' => $poll->id]));

        $response->assertRedirect(withInfo('You have already vote on this poll. Here are the results.'));

        // TODO: perform additional assertions
    }

    public function testVoteReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->actingAs($user)->post('polls/vote', [
            // TODO: send request data
        ]);

        $response->assertRedirect(withErrors('Bro have already vote on this poll. Your vote has not been counted.'));

        // TODO: perform additional assertions
    }

    public function testVoteValidatesWithAFormRequest()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\PollController::class,
            'vote',
            \App\Http\Requests\VoteOnPoll::class
        );
    }

    // test cases...
}
