<?php

namespace Tests\Todo\Feature\Http\Controllers;

use App\Models\Forum;
use App\Models\Subscription;
use App\Models\Topic;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SubscriptionController
 */
class SubscriptionControllerTest extends TestCase
{
    use RefreshDatabase;

    public function testSubscribeForumReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $subscription = Subscription::factory()->create();
        $forum = Forum::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('subscribe_forum', ['route' => $subscription->route, $forum]));

        $response->assertRedirect(withSuccess('You are now subscribed to forum, '.$forum->name.'. You will now receive site notifications when a topic is started.'));

        // TODO: perform additional assertions
    }

    public function testSubscribeTopicReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $subscription = Subscription::factory()->create();
        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('subscribe_topic', ['route' => $subscription->route, $topic]));

        $response->assertRedirect(withSuccess('You are now subscribed to topic, '.$topic->name.'. You will now receive site notifications when a reply is left.'));

        // TODO: perform additional assertions
    }

    public function testUnsubscribeForumReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $subscription = Subscription::factory()->create();
        $forum = Forum::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('unsubscribe_forum', ['route' => $subscription->route, $forum]));

        $response->assertRedirect(withSuccess('You are no longer subscribed to forum, '.$forum->name.'. You will no longer receive site notifications when a topic is started.'));

        // TODO: perform additional assertions
    }

    public function testUnsubscribeTopicReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $subscription = Subscription::factory()->create();
        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('unsubscribe_topic', ['route' => $subscription->route, $topic]));

        $response->assertRedirect(withSuccess('You are no longer subscribed to topic, '.$topic->name.'. You will no longer receive site notifications when a reply is left.'));

        // TODO: perform additional assertions
    }

    // test cases...
}
