<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ThankController
 */
class ThankControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $thank = factory(\App\Models\Thank::class)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('thanks.store', ['id' => $thank->id]));

        $response->assertRedirect(withErrors('You Cannot Thank Your Own Torrent!'));

        // TODO: perform additional assertions
    }

    // test cases...
}
