<?php

namespace Tests\Todo\Feature\Http\Controllers;

use App\Models\Thank;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ThankController
 */
class ThankControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $thank = Thank::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('thanks.store', ['id' => $thank->id]));

        $response->assertRedirect(withErrors('You Cannot Thank Your Own Torrent!'));

        // TODO: perform additional assertions
    }

    // test cases...
}
