<?php

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

uses(TestCase::class);
uses(RefreshDatabase::class);

/**
 * @see \App\Http\Controllers\TopicLabelController
 */
test('approve returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('topics.approve', ['id' => $id]));

    $response->assertRedirect(withInfo('Label Change Has Been Applied'));

    // TODO: perform additional assertions
});

test('bug returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('topics.bug', ['id' => $id]));

    $response->assertRedirect(withInfo('Label Change Has Been Applied'));

    // TODO: perform additional assertions
});

test('deny returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('topics.deny', ['id' => $id]));

    $response->assertRedirect(withInfo('Label Change Has Been Applied'));

    // TODO: perform additional assertions
});

test('implement returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('topics.implement', ['id' => $id]));

    $response->assertRedirect(withInfo('Label Change Has Been Applied'));

    // TODO: perform additional assertions
});

test('invalid returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('topics.invalid', ['id' => $id]));

    $response->assertRedirect(withInfo('Label Change Has Been Applied'));

    // TODO: perform additional assertions
});

test('solve returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('topics.solve', ['id' => $id]));

    $response->assertRedirect(withInfo('Label Change Has Been Applied'));

    // TODO: perform additional assertions
});

test('suggest returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('topics.suggest', ['id' => $id]));

    $response->assertRedirect(withInfo('Label Change Has Been Applied'));

    // TODO: perform additional assertions
});
