<?php

namespace Tests\Todo\Feature\Http\Controllers;

use PHPUnit\Framework\Attributes\Test;
use App\Models\Topic;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\TopicController
 */
final class TopicControllerTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function add_form_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('topics.create', ['id' => $topic->id]));

        $response->assertRedirect(withErrors('You Cannot Start A New Topic Here!'));

        // TODO: perform additional assertions
    }

    #[Test]
    public function close_topic_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('topics.close', ['id' => $topic->id]));

        $response->assertRedirect(withSuccess('This Topic Is Now Closed!'));

        // TODO: perform additional assertions
    }

    #[Test]
    public function delete_topic_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('topics.delete', ['id' => $topic->id]));

        $response->assertRedirect(withSuccess('This Topic Is Now Deleted!'));

        // TODO: perform additional assertions
    }

    #[Test]
    public function edit_form_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('topics.edit', ['id' => $topic->id]));

        $response->assertOk();
        $response->assertViewIs('forum.topic.edit');
        $response->assertViewHas('topic');
        $response->assertViewHas('categories');

        // TODO: perform additional assertions
    }

    #[Test]
    public function edit_topic_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->post(route('topics.update', ['id' => $topic->id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withSuccess('Topic Successfully Edited'));

        // TODO: perform additional assertions
    }

    #[Test]
    public function new_topic_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->post(route('topics.store', ['id' => $topic->id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withErrors('You Cannot Start A New Topic Here!'));

        // TODO: perform additional assertions
    }

    #[Test]
    public function open_topic_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('topics.open', ['id' => $topic->id]));

        $response->assertRedirect(withSuccess('This Topic Is Now Open!'));

        // TODO: perform additional assertions
    }

    #[Test]
    public function pin_topic_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('topics.pin', ['id' => $topic->id]));

        $response->assertRedirect(withSuccess('This Topic Is Now Pinned!'));

        // TODO: perform additional assertions
    }

    #[Test]
    public function topic_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('topics.show', ['id' => $topic->id]));

        $response->assertRedirect(withErrors('You Do Not Have Access To Read This Topic!'));

        // TODO: perform additional assertions
    }

    #[Test]
    public function unpin_topic_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $topic = Topic::factory()->create();
        $user = User::factory()->create();

        $response = $this->actingAs($user)->get(route('topics.unpin', ['id' => $topic->id]));

        $response->assertRedirect(withSuccess('This Topic Is Now Unpinned!'));

        // TODO: perform additional assertions
    }

    // test cases...
}
