<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\WishController
 */
class WishControllerTest extends TestCase
{
    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $wish = factory(\App\Models\Wish::class)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('wishes.destroy', ['id' => $wish->id]));

        $response->assertRedirect(withSuccess('Wish Successfully Removed!'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $wish = factory(\App\Models\Wish::class)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('wishes.index', ['username' => $wish->username]));

        $response->assertOk();
        $response->assertViewIs('user.wishlist');
        $response->assertViewHas('user');
        $response->assertViewHas('wishes');
        $response->assertViewHas('route');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->post(route('wishes.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(withErrors('Wish already exists!'));

        // TODO: perform additional assertions
    }

    // test cases...
}
